AstarNetwork/Astar

.github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md
=> Create PR Template and CONTIBUTION document.

.github/PULL_REQUEST_TEMPLATE.md
Nothing.
Not yet defined commit message rules.
* * *
=> Fix PullRequest Template.

.editorconfig, runtime/src/lib.rs, runtime/src/template.rs
All Project, Editor Config.
Introduce EditorConfig. Reference (https://github.com/paritytech/substrate/blob/master/.editorconfig).
All contributors should adhere to the [house coding style](https://wiki.parity.io/Substrate-Style-Guide).
* * *
=> Introduce EditorConfig.

core/utxo/src/lib.rs, core/utxo/src/mvp.rs
no problem.
refactor utxo-like srml.
It is pluggable Transaction data structure and Value data strucutre. 
* * *
=> Refactor utxo

README.md
=> Additonal README (JP)

Cargo.lock, core/merkle/Cargo.toml, core/merkle/src/lib.rs, core/merkle/src/mock.rs, core/merkle/src/tests.rs, core/utxo/Cargo.toml, core/utxo/src/lib.rs, core/utxo/src/mvp.rs, core/utxo/src/tests.rs, runtime/Cargo.toml, runtime/src/lib.rs
=> Include PlasmMerkle in PlasmUTXO

Cargo.lock, core/merkle/Cargo.toml, core/merkle/src/lib.rs, core/merkle/src/mock.rs, core/merkle/src/tests.rs, core/parent/Cargo.toml, core/parent/src/lib.rs, core/parent/src/mvp.rs, core/primitives/src/lib.rs, core/primitives/src/mvp.rs, core/utxo/src/mvp.rs, core/utxo/src/tests.rs
Implements Parent Chain MVP.
* * *
=> Implements Parent Chain MVP.

README.md
=> Add Readme How to install and write Trait with Parent.

Cargo.lock, Cargo.toml, ci/script.sh
Apply all tests.(add workspace in top cargo file)
* * *
=> Apply all test

Cargo.lock, Cargo.toml, README.md, ci/script.sh
=> Change readme fix

Cargo.lock, Cargo.toml, core/parent/pgspec/Cargo.toml, core/parent/pgspec/src/lib.rs, core/parent/pgspec/src/tests.rs
Parent PGSpec interface. Only Templates. Wrapped SRML-Contract.
* * *
=> Add Parent PGSpec interface

README.md
=> add readme comunity

contracts/deposit/Cargo.toml, contracts/deposit/src/lib.rs
Deposit contracts use pritmives.
* * *
=> Deposit contracts use pritmives.

Cargo.lock, contracts/deposit/Cargo.toml, contracts/deposit/src/lib.rs, contracts/primitives/Cargo.toml
https://docs.plasma.group/projects/spec/en/latest/src/02-contracts/deposit-contract.html?highlight=depositedRangeId#
* * *
=> Impl DepositContract only interface.

ci/script.sh, contracts/commitment/Cargo.toml, contracts/commitment/Makefile, contracts/commitment/src/default.rs, contracts/commitment/src/lib.rs, contracts/commitment/src/traits.rs, contracts/primitives/src/lib.rs, contracts/primitives/src/traits.rs
=> Impl commitment

ci/script.sh, contracts/deposit/src/default.rs, contracts/deposit/src/traits.rs, contracts/predicate/Makefile, contracts/predicate/src/lib.rs, contracts/predicate/src/ownership.rs, contracts/predicate/src/traits.rs, contracts/primitives/src/lib.rs
=> Impl predicate

contracts/commitment/src/lib.rs, contracts/commitment/src/merkle.rs, contracts/deposit/Cargo.toml, contracts/deposit/src/default.rs, contracts/primitives/src/lib.rs
Add Deposite Contract Trait tests.
* * *
=> Add Deposit Test

contracts/predicate/src/ownership.rs
=> Add predicate test

.travis.yml, Cargo.lock, Cargo.toml, node/cli/build.rs, node/runtime/build.rs
=> Build passed travis.

ci/script.sh
No
Synchronized with current substrate CI script.
* * *
=> Fix TravisCI builds

Cargo.lock, node/runtime/Cargo.toml, node/runtime/src/lib.rs, srml/operator/src/lib.rs, srml/operator/src/parameters.rs
Operator module in runtime.
* * *
=> impl operator for runtime

Cargo.lock, contracts/commitment/Cargo.toml, contracts/primitives/Cargo.toml, node/cli/Cargo.toml, node/executor/Cargo.toml, node/primitives/Cargo.toml, node/rpc/Cargo.toml, node/runtime/Cargo.toml, node/runtime/build.rs, srml/operator/Cargo.toml
* Fork substrate repository to organisation
* Fix commit of used substrate in plasm-master branch
* * *
=> Fix version of used substrate

type.json
=> Add type.json

third-party/docker/Makefile
=> Fix docker images.

bin/node/runtime/src/lib.rs
=> increment spec version

.editorconfig
Depends on.
https://github.com/staketechnologies/Plasm/issues/90
* * *
=> update editor conifg follows on ink!

.editorconfig, .github/workflows/dockerpush.yml
https://github.com/staketechnologies/Plasm/issues/95
Triggered
- push master : `staketechnologies/plasm-node:latest`
- push tag `v*`: `staketechnologies/plasm-node:*` 
* * *
=> Add docker push

frame/plasm-staking/src/tests.rs
=> Fix plasm staking test

frame/operator/src/lib.rs, frame/operator/src/tests.rs, frame/plasm-staking/src/tests.rs
For fetching all contracts by client application.
* * *
=> Use linked_map operator

.github/workflows/dockerpush.yml, README.md, contracts/balances/.ink/abi_gen/Cargo.toml, contracts/cash/.ink/abi_gen/Cargo.toml, contracts/commitment/Cargo.toml, contracts/deposit/Cargo.toml, contracts/predicate/Cargo.toml, contracts/primitives/Cargo.toml, third-party/docker/Dockerfile, third-party/docker/Makefile, third-party/docker/plasm_builder/Dockerfile
Bugfix docker buildings.
* * *
=> Fix docker

.github/workflows/crates.yml
* * *
https://github.com/staketechnologies/Plasm/issues/101
=> add update crates

Cargo.lock, Cargo.toml, frame/operator/src/lib.rs, frame/operator/src/parameters.rs, frame/operator/src/tests.rs, frame/trading/Cargo.toml, frame/trading/src/lib.rs, frame/trading/src/tests.rs
Add an operator trading modules.
This can be:
- offer
- reject
- accept
- remove
Next PR, I will add this module to runtime.
We can not confirm the `lock` test. So, we may be updated plasm-master branch.
* * *
=> Feature trading

Cargo.lock, bin/node/cli/Cargo.toml, bin/node/cli/bin/main.rs, bin/node/cli/build.rs, bin/node/cli/src/browser.rs, bin/node/cli/src/chain_spec.rs, bin/node/cli/src/cli.rs, bin/node/cli/src/command.rs, bin/node/cli/src/lib.rs, bin/node/cli/src/service.rs, bin/node/executor/Cargo.toml, bin/node/primitives/Cargo.toml, bin/node/rpc/Cargo.toml, bin/node/rpc/src/lib.rs, bin/node/runtime/Cargo.toml, bin/node/runtime/build.rs, bin/node/runtime/src/impls.rs, bin/node/runtime/src/lib.rs, frame/operator/src/lib.rs, frame/operator/src/tests.rs, frame/plasm-staking/src/lib.rs, frame/plasm-staking/src/mock.rs, frame/plasm-staking/src/parameters.rs, frame/plasm-staking/src/tests.rs, frame/trading/Cargo.toml, frame/trading/src/lib.rs, frame/trading/src/tests.rs
Trading module into the runtime.
1. construct_runtime! has a trading module
2. staketechnologies/substrate plasm-master branch is updated.
3. add TODO tests on trading module
4. Fix all sources updated by plasm-master.
https://github.com/staketechnologies/substrate
* * *
=> Feature trading into the runtime

.github/workflows/crates.yml, .github/workflows/dockerpush.yml
=> Fix workflows

Cargo.lock, frame/plasm-lockdrop/Cargo.toml, frame/plasm-lockdrop/src/eth_utils.rs, frame/plasm-lockdrop/src/lib.rs
=> pallet-plasm-lockdrop: add Ethereum lockdrop support

.github/workflows/crates.yml, Cargo.lock, bin/node/cli/Cargo.toml, bin/node/cli/src/chain_spec.rs, bin/node/cli/src/command.rs, bin/node/cli/src/lib.rs, bin/node/cli/src/service.rs, bin/node/runtime/Cargo.toml, bin/node/runtime/src/lib.rs, frame/operator/src/lib.rs, frame/plasm-lockdrop/Cargo.toml, frame/plasm-lockdrop/mock.rs, frame/plasm-lockdrop/src/lib.rs, frame/plasm-lockdrop/tests.rs, frame/plasm-staking/src/lib.rs, frame/plasm-staking/src/mock.rs, frame/trading/src/lib.rs, third-party/nix/release.nix
Upgrading node and modules to latest substrate release: https://github.com/paritytech/substrate/releases/tag/v2.0.0-alpha.4
* * *
=> Upgrade to substrate 2.0-alpha4

.github/workflows/crates.yml, .github/workflows/dockerpush.yml
=> Fix docker push and Triggered dusty

bin/node/cli/Cargo.toml, bin/node/primitives/Cargo.toml, bin/node/rpc/Cargo.toml, bin/node/runtime/Cargo.toml, bin/node/runtime/src/lib.rs
> Nothing special, just bump versions.
=> Plasm release 1.0.0 for Dusty Network

Cargo.lock, Cargo.toml, frame/ovm/src/lib.rs, frame/plasma/Cargo.toml, frame/plasma/rpc/runtime-api/Cargo.toml, frame/plasma/rpc/runtime-api/src/lib.rs, frame/plasma/src/lib.rs, frame/plasma/src/mock.rs, frame/plasma/src/tests.rs
#160 
The ref: https://docs.plasmnet.io/TechnicalChapter/OVM.html
This is an implementation of the Plasma module. What is still unimplemented are the hash functions and the Deposit Contract.
The hash function needs to be updated to the Substrate to reflect this commit.
https://github.com/paritytech/substrate/pull/6101
Ovm module is must be implemented when using the Plasma module. And Plasma module uses some ovm data types.
* * *
=> Plasma module Part1

bin/node/runtime/src/lib.rs
=> enable dapps staking

third-party/docker/plasm_builder/Dockerfile
=> Fix plasm builder For dusty

.github/workflows/integration.yml
**Motivation**
Fix CI build for Nix: update to latest actions `v10`.
* * *
=> [CI]: bump nix actions version

README.md
=> Fix node install command

Cargo.lock, bin/node/cli/Cargo.toml, bin/node/cli/lockdrop-oracle/Cargo.toml, bin/node/cli/lockdrop-oracle/src/btc_utils.rs, bin/node/cli/lockdrop-oracle/src/lib.rs, bin/node/primitives/Cargo.toml, bin/node/rpc/Cargo.toml, bin/node/runtime/Cargo.toml, bin/node/runtime/src/lib.rs, bin/subkey/Cargo.toml
=> Dusty release 1.2.0

Cargo.lock, bin/node/cli/lockdrop-oracle/Cargo.toml, bin/node/cli/lockdrop-oracle/src/btc_utils.rs, bin/node/cli/lockdrop-oracle/src/cli.rs, bin/node/cli/lockdrop-oracle/src/eth_utils.rs, bin/node/cli/lockdrop-oracle/src/lib.rs, bin/node/cli/src/chain_spec.rs, bin/node/runtime/src/lib.rs, frame/dapps-staking/Cargo.toml, frame/dapps-staking/src/lib.rs, frame/operator/Cargo.toml, frame/operator/src/lib.rs, frame/ovm/Cargo.toml, frame/plasm-lockdrop/Cargo.toml, frame/plasm-lockdrop/src/lib.rs, frame/plasm-lockdrop/src/mock.rs, frame/plasm-lockdrop/src/tests.rs, frame/plasm-rewards/Cargo.toml, frame/plasm-rewards/src/inflation.rs, frame/plasm-rewards/src/traits.rs, frame/plasm-validator/Cargo.toml, frame/plasma/Cargo.toml, frame/trading/Cargo.toml, ovmi/cli/Cargo.toml, ovmi/lib/Cargo.toml
=> Improved pallet-plasm-lockdrop errors and tests

.github/workflows/crates.yml, .github/workflows/dockerpush.yml, .github/workflows/integration.yml, Cargo.lock, bin/node/cli/Cargo.toml, bin/node/cli/src/chain_spec.rs, bin/node/primitives/Cargo.toml, bin/node/rpc/Cargo.toml, bin/node/runtime/Cargo.toml, bin/node/runtime/src/lib.rs, frame/plasm-lockdrop/src/lib.rs, frame/plasm-lockdrop/src/mock.rs
=> Dusty release 1.2.1 

bin/node/cli/lockdrop-oracle/Cargo.toml, bin/node/cli/lockdrop-oracle/abis/chainlink.json, bin/node/cli/lockdrop-oracle/src/chainlink.rs, bin/node/cli/lockdrop-oracle/src/lib.rs
=> Lockdrop oracle Chainlink price feed

bin/node/cli/lockdrop-oracle/src/lib.rs
=> Fix BTC oracle outputs matching

.github/workflows/crates_frame.yml, Cargo.lock, frame/dapps-staking/Cargo.toml, frame/operator/Cargo.toml, frame/ovm/Cargo.toml, frame/plasm-validator/Cargo.toml, frame/plasma/Cargo.toml, frame/trading/Cargo.toml, ovmi/lib/Cargo.toml
=> Fix cargo publish

frame/dapps-staking/src/lib.rs, frame/dapps-staking/src/log.rs, frame/dapps-staking/src/rewards.rs, frame/dapps-staking/src/tests.rs
- change calculation of rewards
* * *
=> modify community rewards

README.md
Fix tag name for node installation in README
=> Fix node version tag for installing from source command

bin/node/cli/lockdrop-oracle/src/chainlink.rs
=> Updated chainlink aggregator addresses

frame/dapps-staking/src/lib.rs, frame/dapps-staking/src/tests.rs
- add voting system
- add slashing or locking depends votes
* * *
=> Add Good/Bad voting

.github/workflows/integration.yml, Cargo.lock, Cargo.toml, bin/node/cli/src/chain_spec.rs, bin/node/runtime/Cargo.toml, bin/node/runtime/src/lib.rs, frame/plasm-lockdrop/src/lib.rs, frame/plasm-lockdrop/src/mock.rs, frame/utility/Cargo.toml, frame/utility/src/lib.rs, frame/utility/src/tests.rs, third-party/nix/release.nix
=> Enabled pallet_utility for batch calls

Cargo.lock, bin/node/runtime/Cargo.toml, bin/node/runtime/src/lib.rs, frame/balances/Cargo.toml, frame/balances/src/benchmarking.rs, frame/balances/src/lib.rs, frame/balances/src/tests.rs, frame/balances/src/tests_composite.rs, frame/balances/src/tests_local.rs, third-party/nix/release.nix, third-party/nix/shell.nix
=> Lock transfer transactions

bin/node/runtime/src/lib.rs, frame/custom-signatures/src/ethereum.rs, frame/custom-signatures/src/lib.rs
=> Using Vec type for custom signatures argument

README.md
=> Modify Typos

frame/dapps-staking/src/lib.rs, frame/dapps-staking/src/mock.rs, frame/dapps-staking/src/tests.rs
- changed the claim specification as specify the address of contracts
ref #255 
* * *
=> change claim specification

.gitmodules, Cargo.lock, bin/node/cli/src/chain_spec.rs, bin/node/runtime/Cargo.toml, bin/node/runtime/src/lib.rs
=> Enabled XTokens pallet

Cargo.lock, Cargo.toml, frame/dapps-staking/Cargo.toml, frame/dapps-staking/src/lib.rs, frame/operator/Cargo.toml, frame/operator/src/lib.rs, frame/plasm-support/Cargo.toml, frame/plasm-support/src/lib.rs, frame/plasm-validator/Cargo.toml, frame/trading/Cargo.toml, frame/trading/src/lib.rs
related to https://github.com/PlasmNetwork/Plasm/issues/111
@satellitex, please check
there were many Cargo.lock changes
=> Move helper traits to new pkg plasm-support

Cargo.lock, bin/node/runtime/Cargo.toml, frame/trading/Cargo.toml, frame/trading/src/lib.rs, frame/trading/src/tests.rs
=> update operator-trading on latest dusty

frame/plasma/src/lib.rs, frame/plasma/src/mock.rs, frame/plasma/src/tests.rs
=> Feat verify inclusion test

frame/ovm/src/lib.rs, frame/plasma/src/checkpoint.rs, frame/plasma/src/exit.rs, frame/plasma/src/helper.rs, frame/plasma/src/lib.rs, frame/plasma/src/mock.rs, frame/plasma/src/tests.rs, frame/plasma/tests/ownership.json
Closed https://github.com/PlasmNetwork/Plasm/issues/313
=> [Plasma] Refactor exteranal call of exit Dispute in plasma module

.gitmodules, Cargo.lock, bin/collator/Cargo.toml, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
This is a hotfix that upgrades the Shiden collator to the latest version of polkadot.
* * *
=> Upgrade shiden collator to 0.9.8

bin/node/runtime/src/lib.rs
This commit fixed gas price of the dusty
=> Adjust fixed gas price

bin/node/runtime/Cargo.toml, bin/node/runtime/src/lib.rs
=> fix dusty high fee

bin/node/Cargo.toml, bin/node/cli/Cargo.toml, bin/node/primitives/Cargo.toml, bin/node/rpc/Cargo.toml, bin/node/runtime/Cargo.toml, bin/node/runtime/src/lib.rs
=> update astar versions to 1.10.0, minor fmt fix

README.md
Add deprecation message to `README.md`.
=> add deprecation message

README.md, third-party/nix/release.nix, third-party/nix/shell.nix
* Nix build
* Updated Nix to use:
* new libclang lib path
* new rustc nightly version
* Updated README.md
* * *
=> Fix for Nix Dusty integration problem

Cargo.lock
None
Updated used _parity-db_ version to avoid problems
with parsing .toml file in nix build.
* * *
=> Update parity-db version to fix parsing error

Cargo.lock, Cargo.toml, frame/block-reward/Cargo.toml, frame/block-reward/src/lib.rs
The Block Reward pallet should handle inflation in a parachain. This implements a minimalistic helper for inflation minting and distribution. It excludes complex approaches for inflation because of limited resources in a parachain.
* * *
=> Added Pallet Block Reward

README.md
Updates the README file and add build guides
* * *
=> Update Astar readme file

bin/collator/res/shiden.json, bin/collator/res/shiden.raw.json, bin/collator/src/service.rs, runtime/shiden/src/lib.rs
=> Shiden runtime v5

runtime/shiden/src/lib.rs
One hour for session duration looks much more convenient in practice:
* quick session key rotation;
* quick offline collator kick;
* quick collator onboarding.
* * *
=> One hour session duration

README.md
- Updated the README to add more status badges and a build guide
* * *
=> updated Shiden readme

Cargo.lock, Cargo.toml, bin/collator/Cargo.toml, bin/collator/src/aura_upgrade.rs, bin/collator/src/command.rs, bin/collator/src/lib.rs, bin/collator/src/primitives.rs, bin/collator/src/rpc.rs, bin/collator/src/service.rs, frame/block-reward/Cargo.toml, frame/custom-signatures/Cargo.toml, frame/custom-signatures/src/ethereum.rs, frame/custom-signatures/src/lib.rs, frame/custom-signatures/src/tests.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
* Enabled pallet_multisig in runtime
* Ported pallet_custom_signatures to FRAME 2.0
* Enabled pallet_custom_signatures with Ethereum signatures on runtime
* Switch to polkadot-v0.9.9 release
* Added payment-info RPC service
* Bump runtime version
* * *
=> Support for multi- and custom-signatures

bin/collator/res/shiden.json, bin/collator/res/shiden.raw.json, bin/collator/src/command.rs
Quick fix for shiden chain spec.
* * *
=> Fix shiden spec (drop `lightSyncState` field)

.github/workflows/srtool.yml
Fix indentation of srtool action. This PR fixes the issue missed from reviewing https://github.com/PlasmNetwork/Astar/pull/382
P.S.
@Maar-io sorry, I should have properly checked the indentation on the previous PR. My bad!
* * *
=> fix srtool action condition

Cargo.lock, bin/collator/Cargo.toml, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
Collators should be rewarded for transaction processing.
* * *
=> Added DealWithFees handler for tx fees

runtime/shiden/src/lib.rs
=> Temporary disable custom signatures pallet

Cargo.lock, frame/custom-signatures/Cargo.toml, frame/custom-signatures/src/lib.rs, frame/custom-signatures/src/tests.rs
* Added `nonce` field as argument of call, when account send transaction it increments and makes concurrent transactions invalid.
* Added constant transaction fee to prevent tx spam attack
* Added transaction prefix to prevent tx replay to other chains 
* * *
=> Fix custom signatures pallet

frame/dapps-staking/src/lib.rs, frame/dapps-staking/src/mock.rs, frame/dapps-staking/src/pallet/mod.rs, frame/dapps-staking/src/tests.rs
This is a development PR for dapps-staking step1.
It is still work in progress
=> dapps-staking step1.

runtime/shibuya/src/lib.rs, runtime/shiden/src/lib.rs
=> Fix EVM gas fee charge

frame/dapps-staking/src/mock.rs, frame/dapps-staking/src/pallet/mod.rs, frame/dapps-staking/src/tests.rs
added era handling in the on_initialize()
=> dapps-staking Era handling

frame/dapps-staking/src/lib.rs, frame/dapps-staking/src/pallet/mod.rs
added storage items
- PalletEraRewards
- ContractEraStake
- ContractLastClaimed
- ContractLastStaked
=> added new storage maps

CONTRIBUTING.md
Fixes the URL in the contribution document
* * *
=> fix url in contribution guide

Cargo.toml
=> Update Cargo.toml dApp staking license  

Cargo.lock, Cargo.toml, frame/dapps-staking/Cargo.toml
None
Moved dapps staking license to dapps staking toml.
* * *
=> License move to dapps

frame/dapps-staking/src/mock.rs, frame/dapps-staking/src/tests.rs
ASTL instead of SDN
not corrected on all places
=> test failing due to wrong name

frame/dapps-staking/src/mock.rs, frame/dapps-staking/src/pallet/mod.rs, frame/dapps-staking/src/tests.rs
reading era_reward_and_stake() from the wrong era
=> wrong era to read EraRewardsAndStakes

frame/dapps-staking/src/mock.rs, frame/dapps-staking/src/pallet/mod.rs, frame/dapps-staking/src/testing_utils.rs, frame/dapps-staking/src/tests.rs
=> refactoring claim UTs

bin/collator/src/command.rs, bin/collator/src/parachain/chain_spec.rs, third-party/polkadot-launch/config.json
Added polkadot-launch config as an option to launch parachain testnet locally.
* * *
=> Added polkadot-launch support

.github/PULL_REQUEST_TEMPLATE.md
=> changed pr template

Cargo.toml, frame/dapps-staking/src/mock.rs, frame/dapps-staking/src/pallet/mod.rs, frame/dapps-staking/src/tests.rs
=> Added register deposit function

README.md
changes the repo cover image to a gif
* * *
=> changed image to gif

Cargo.lock, bin/collator/src/local/chain_spec.rs, runtime/local/Cargo.toml, runtime/local/src/lib.rs
=> Adding Vesting pallet for the local network

Cargo.lock
fix frontier bug, requested by anyswap
* * *
=> Update frontier commit

.github/workflows/srtool.yml, Cargo.lock, bin/collator/Cargo.toml, frame/block-reward/Cargo.toml, frame/block-reward/src/lib.rs, frame/custom-signatures/Cargo.toml, frame/dapps-staking/Cargo.toml, precompiles/staking/Cargo.toml, runtime/local/Cargo.toml, runtime/local/src/lib.rs, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
=> Dapp rewards release preparation

.github/workflows/srtool.yml
> Increase subwasm in CI to 0.14.1
**Check list**
**Changes**
- Increase subwasm version to avoid error in CI
=> Bump subwasm version

.github/workflows/integration.yml, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
> Add CI for runtime-benchmarks and try-runtime.
**Check list**
**Adds**
- CI for try-runtime. Checks if it's possible to compile try-runtime using the latest updates.
- CI for runtime-benchmarks. Builds an optimized binary which can be used for running benchmarks. This is useful since it takes a lot of time to build a benchmarking binary.
=> Added CI for runtime-benchmarks and try-runtime

Cargo.lock, bin/collator/Cargo.toml, frame/dapps-staking/Cargo.toml, frame/dapps-staking/README.md, frame/dapps-staking/src/mock.rs, frame/dapps-staking/src/pallet/mod.rs, frame/dapps-staking/src/tests.rs, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/local/src/lib.rs, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
Ensure minimum remaining transferable balance after staking.
> Minimum transferable balance after stake
**Check list**
**Changes**
- stake functionality in dapps staking will now ensure a minimum remaining transferable balance
=> Minimum remaining transferable balance after stake

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**
=> Burn 20% of shiden tx fees

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shiden/Cargo.toml
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**
=> Fix Shiden eth_blockByNumber calls

.github/workflows/crates.yml, .github/workflows/integration.yml, Cargo.lock, bin/collator/Cargo.toml, frame/block-reward/Cargo.toml, frame/custom-signatures/Cargo.toml, frame/dapps-staking/Cargo.toml, precompiles/staking/Cargo.toml, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs, third-party/nix/release.nix
Upgrade to latest Polkadot release, fix CI & tests.
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**
=> Bump polkadot/substrate to v0.9.12

runtime/shibuya/src/lib.rs, runtime/shiden/src/lib.rs
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**
=> Increase stakers reward from 20% to 50%

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
* set max stakers to 512
*  set minimum stake to 50 SDN
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**
=> Rollback max stakers in shiden

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**
=> Added storage version migration

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/local/src/lib.rs, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**
=> EVM: added self-contained call

Cargo.lock, bin/collator/Cargo.toml, bin/collator/res/astar.json, bin/collator/res/astar.raw.json, bin/collator/res/shibuya.json, bin/collator/res/shibuya.raw.json, bin/collator/res/shiden.json, bin/collator/res/shiden.raw.json, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shiden/Cargo.toml
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**
=> Added ss58format property

Cargo.lock, bin/collator/Cargo.toml, frame/dapps-staking/Cargo.toml, frame/dapps-staking/src/pallet/mod.rs, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
> Address audit comments
**Check list**
=> dApps staking audit fixes

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shiden/Cargo.toml
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**
=> Fix eth_getBlockByHash for Shiden

.github/workflows/integration.yml
Cleanup test build artifacts to release more space before optimized builds.
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**
=> Fix CI storage limit issue

Cargo.lock, bin/collator/Cargo.toml, bin/collator/res/astar.json, bin/collator/res/astar.raw.json, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shiden/Cargo.toml
This is Astar parachain launch PR.
**Check list**
=> Astar launch release

Cargo.lock, bin/collator/Cargo.toml, bin/collator/res/shibuya.json, bin/collator/res/shibuya.raw.json, bin/collator/src/parachain/chain_spec/shibuya.rs, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shiden/Cargo.toml
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**
=> Rollback shibuya testnet

Cargo.lock, bin/collator/Cargo.toml, bin/collator/res/astar.json, bin/collator/res/astar.raw.json, bin/collator/res/shibuya.json, bin/collator/res/shibuya.raw.json, bin/collator/res/shiden.json, bin/collator/res/shiden.raw.json, bin/collator/src/parachain/chain_spec/astar.rs, bin/collator/src/parachain/chain_spec/mod.rs, bin/collator/src/parachain/chain_spec/shibuya.rs, bin/collator/src/parachain/chain_spec/shiden.rs, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shiden/Cargo.toml
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**
=> Rollback shibuya & fix relay selection

bin/collator/res/astar.json, bin/collator/res/astar.raw.json
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**
=> Add EU bootnode

scripts/graph.sh, scripts/rpc.sh
Startup script for shiden RPC nodes.
=> Add one-line startup script for RPC

bin/collator/res/astar.json, bin/collator/res/astar.raw.json
**Check list**
**Adds**
**Fixes**
Fix EU bootnode address
**Changes**
**To-dos**
=> Astar bootnode patch

Cargo.lock, bin/collator/Cargo.toml
Fix for runtime benchmark compilation issue.
**Check list**
=> Fix runtime-benchmarks compilation issue

Cargo.lock, Cargo.toml, bin/collator/Cargo.toml, bin/collator/src/local/chain_spec.rs, bin/collator/src/local/service.rs, bin/collator/src/parachain/chain_spec/astar.rs, bin/collator/src/parachain/chain_spec/shibuya.rs, bin/collator/src/parachain/chain_spec/shiden.rs, bin/collator/src/parachain/service.rs, bin/collator/src/rpc.rs, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/astar/src/precompiles.rs, runtime/local/Cargo.toml, runtime/local/src/lib.rs, runtime/local/src/precompiles.rs, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shibuya/src/precompiles.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs, runtime/shiden/src/precompiles.rs
This PR implements latest London release EVM for Astar / Shiden runtimes.
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**
=> Bring London EVM to Astar

Cargo.lock, bin/collator/Cargo.toml, bin/collator/src/local/service.rs, bin/collator/src/parachain/service.rs, bin/collator/src/rpc.rs, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/local/src/lib.rs, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
This PR should fix eth_getBalance issue on Shiden.
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**
=> Update frontier version

CONTRIBUTING.md, Cargo.lock, README.md, bin/collator/Cargo.toml, bin/collator/src/command.rs, bin/collator/src/local/chain_spec.rs, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/local/src/lib.rs, runtime/local/src/precompiles.rs, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shibuya/src/precompiles.rs, runtime/shiden/Cargo.toml
Adding ds-precompile to Local and Shibuya runtimes with polkadot-v0.9.16
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**
=> Adding ds-precompile to Local and Shibuya runtimes with polkadot-v0.9.16

.github/workflows/integration.yml, Cargo.lock, bin/collator/Cargo.toml
* Changed `astar-frame` dependencies to use tags instead of default `0.9.16` branch
* fixed issue with runtime-benchmarks build
**Check list**
=> Runtime-benchmark fix & small CI improvements

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
Update runtimes to use tags for dapps-staking dependencies.
This is needed since we will soon merge new features which could
cause problems or break build.
**Check list**
=> Tag usage & version uplift

Cargo.lock, bin/collator/Cargo.toml, bin/collator/src/parachain/service.rs, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shiden/Cargo.toml
This PR introduce WASM contracts RPC for Shibuya public nodes.
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**
=> Fix Shibuya WASM contracts rpc

CONTRIBUTING.md, Cargo.lock, Cargo.toml, bin/collator/Cargo.toml, bin/collator/src/cli.rs, bin/collator/src/local/service.rs, bin/collator/src/parachain/service.rs, bin/collator/src/rpc.rs, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/local/src/lib.rs, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
* Uplifted polkadot to version `polkadot-v0.9.17`
* Removed some unused dependencies
**TODO**
**Check list**
=> Uplift to polkadot-v0.9.17

.github/workflows/crates.yml, .github/workflows/integration.yml, .github/workflows/srtool.yml
Use GitHub self hosted actions runner to reduce compilation time
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**
=> self hosted actions runner

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shiden/Cargo.toml
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**
=> Update frontier and fix RPC bug

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml
* Use latest dapps-staking with Shibuya migration fix
**TODO**
**Check list**
=> Shibuya DS-v3 migration fix

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml
> Local and Shibuya updates for Function Modifier
related to https://github.com/AstarNetwork/astar-frame/pull/29
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**
=> Local and Shibuya updates for Function Modifier

.github/workflows/integration.yml
> Improve CI to save time. Please see below about actual changes.
**Check list**
**Adds**
- cargo check --all-features job
- test job. binary build jobs are dependent on this job
**Fixes**
None
**Changes**
- disable nix job
- disable runtime-benchmarks and try-runtime job because they are parts of all-features job
- Use cache for building release binary to save time
- building binary jobs are executed only when push event with tags
**To-dos**
=> Actions workflow improvements

.github/workflows/fmt.yml, .github/workflows/integration.yml, rust-toolchain.toml
Added rust toolchain file to the repository.
Benefit of this is that each time a dev runs `cargo build` or any other check, it will force it to use the nightly
version defined in the toml file. This means that we will ensure more comparable builds between different machines/devs.
[More info about the config file](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file)
**Check list**
=> rust-toolchain file & updated CI

.github/workflows/integration.yml
Use cache for test job on the self-hosted actions runner
**Check list**
**Adds**
**Fixes**
**Changes**
- Use cache for test job on the self-hosted actions runner
- nix build after testing
**To-dos**
=> CI test with cache

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml
Check "Required Tasks" in  #552 to see what this currently includes
**Check list**
=> [WIP] Shibuya: dApps Staking 3.1.0 - fixed era lengths #552

.github/workflows/integration.yml
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**
=> Remove caching for UTs

Cargo.lock, bin/collator/Cargo.toml, bin/collator/src/local/chain_spec.rs, bin/collator/src/parachain/chain_spec/shibuya.rs, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/local/src/lib.rs, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
Introduction of dynamic inflation for `local-runtime` and `shibuya-runtime`.
Removed old `block-reward` pallet usage.
**TODO**
**Check list**
=> Dynamic inflation for local & Shibuya

Cargo.lock
Fix lock file issue.
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**
=> Fix lock file

Cargo.lock, bin/collator/Cargo.toml, bin/collator/src/parachain/chain_spec/astar.rs, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/astar/src/precompiles.rs, runtime/astar/src/weights/pallet_dapps_staking.rs, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shiden/Cargo.toml
Introduces various new features to Astar.
* Individual claim
* Block reward v2
* staking festival reset functionality
**TODO**
**Check list**
=> Astar staking festival reset

Cargo.lock, bin/collator/Cargo.toml, bin/xcm-tools/src/command.rs, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shiden/Cargo.toml
Easter eggs for Astar! :rabbit: 
**Check list**
=> Easter eggs for Astar

Cargo.lock, bin/xcm-tools/Cargo.toml, bin/xcm-tools/src/cli.rs, bin/xcm-tools/src/command.rs, runtime/astar/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs
PR companion of https://github.com/AstarNetwork/astar-frame/pull/35
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**
=> xcm-tools: added AssetId to EVM address conversion

bin/collator/src/local/chain_spec.rs
> Changing wrong key. Use vanity key.
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**
=> Change environment account for evm

CONTRIBUTING.md, Cargo.lock, Cargo.toml, bin/collator/Cargo.toml, bin/collator/src/cli.rs, bin/collator/src/command.rs, bin/collator/src/local/chain_spec.rs, bin/collator/src/local/mod.rs, bin/collator/src/local/service.rs, bin/collator/src/parachain/chain_spec/astar.rs, bin/collator/src/parachain/chain_spec/shibuya.rs, bin/collator/src/parachain/chain_spec/shiden.rs, bin/collator/src/parachain/service.rs, bin/collator/src/parachain/shell_upgrade.rs, bin/collator/src/rpc.rs, bin/xcm-tools/Cargo.toml, bin/xcm-tools/src/command.rs, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/local/src/lib.rs, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shibuya/src/xcm_config.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
Bump substrate from `polkadot-v0.9.17` to `polkadot-v0.9.19`.
**TODO**
**Check list**
=> Feature/polkadot v0.9.19

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs, runtime/shiden/src/xcm_config.rs
Fix for dapps-staking compounding reward data corruption.
**Check list**
=> Restake fix Shibuya/Shiden

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/astar/src/precompiles.rs, runtime/astar/src/xcm_config.rs, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shiden/Cargo.toml
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**
=> Added XCMP into Astar runtime

Cargo.lock, bin/collator/Cargo.toml, bin/collator/src/parachain/chain_spec/astar.rs, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/astar/src/weights/pallet_dapps_staking.rs, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs, runtime/shiden/src/weights/pallet_dapps_staking.rs
* compounding rewards support for Astar
* nomination transfer support for Shiden
* modify `astar-dev` genesis to provide more init funds to Alice and Bob
**Check list**
=> Compounding rewards (Astar) & Nomination transfer (Shiden)

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**
=> Shibuya: Added custom pallet-xcm from astar-frame

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/astar/src/weights/pallet_dapps_staking.rs, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
Adds nomination transfer for dapps-staking to Astar.
Adds custom XCM pallet to Shiden.
**Check list**
=> Nomination transfer for Astar/Custom XCM pallet for Shiden

.github/workflows/integration.yml, Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/astar/src/precompiles.rs, runtime/local/Cargo.toml, runtime/local/src/precompiles.rs, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shibuya/src/precompiles.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs, runtime/shiden/src/precompiles.rs
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**
=> CI improvements

Cargo.lock, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shibuya/src/precompiles.rs, third-party/nix/release.nix
This PR integrates XCM precompile into Shibuya runtime.
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**
=> XCM precompile for Shibuya

third-party/docker/Dockerfile
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**
=> abolish plasm network ref

Cargo.lock, bin/collator/Cargo.toml, bin/xcm-tools/Cargo.toml, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/astar/src/precompiles.rs, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shibuya/src/precompiles.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs, runtime/shiden/src/precompiles.rs
Uplift to `polkadot-v0.9.24`.
**Check list**
=> polkadot-v0.9.24 uplift & ECDSA precompiles

bin/collator/src/rpc.rs
> I added DevApiServer In order to use ClientBuilder and monitor block status from RPC
**Check list**
- Added DevApiServer RPC
**Adds**
- Added DevApiServer RPC
=> Added DevApiServer RPC

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shiden/Cargo.toml
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**
=> Memory leak patch

Cargo.lock, bin/collator/Cargo.toml, runtime/shibuya/Cargo.toml
Fix for logs not being displayed.
**Check list**
=> Fix for logging issue

bin/collator/res/rocstar.json, bin/collator/res/rocstar.raw.json
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**
=> switch chainspecs to Rocstar

.github/workflows/integration.yml
Optimize docker flow to reuse already built linux artifact.
=> Optimize Docker CI Flow

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
This PR fix SlashRation 10% -> 1% on Shibuya and introduce collator slashing on Shiden with same parameters.
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**
=> Fix slash rate on shibuya

Cargo.lock, bin/collator/Cargo.toml, bin/collator/src/parachain/service.rs, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shiden/Cargo.toml
Enable `pallet-contracts-rpc` for Shiden.
**Check list**
=> Enable pallet-contracts RPC

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shiden/Cargo.toml
Revert tracing-core version bump
=> Revert tracing-core version bump

Cargo.lock, runtime/local/Cargo.toml, runtime/local/src/lib.rs
=> [Temp] dapps-staking chain extension

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs, runtime/shiden/src/xcm_config.rs
Added XCM fee handler to Shiden runtime.
**Check list**
=> Shiden XCM fee handler

Cargo.lock, bin/collator/Cargo.toml, bin/collator/src/local/service.rs, bin/collator/src/parachain/service.rs, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/local/src/lib.rs, runtime/local/src/precompiles.rs, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
* integrated `pallet-assets` with the precompiles into local runtime.
* integrated XC20+ into supported runtimes
* included xcm precompiles fixes into all runtimes
* included frontier uplift with fixed caching issue
* improved numeric conversions in runtime
**Check list**
=> astar-frame & frontier uplift

.github/workflows/release.yml, taplo.toml
Fix wasm asset name, added `.wasm` file extension
=> fix wasm asset name

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/astar/src/xcm_config.rs, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shiden/Cargo.toml
Introduces `XcmFeeHandler` for Astar.
This will deposit fees into treasury instead of just burning it.
**Check list**
=> Introduce TakeRevenue handler for Astar

Cargo.lock, bin/collator/Cargo.toml, bin/xcm-tools/Cargo.toml, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
=> Bump polkadot version

.github/workflows/base_checks.yaml, .github/workflows/checks-and-tests.yaml, .github/workflows/release.yml, .github/workflows/static-analysis.yml
* removed cache usage due to issues with size (up to 12GB) which caused problems
* optimize usage of github runner
* remove UT from non-release since it has memory issues
=> CI cache usage removal & small improvements

Cargo.lock, bin/collator/Cargo.toml, bin/collator/src/parachain/chain_spec/astar.rs, bin/collator/src/parachain/chain_spec/shibuya.rs, bin/collator/src/parachain/chain_spec/shiden.rs, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
Migration for `collator-selection` pallet in Astar runtime.
All collators who aren't invulnerable are unlocked and released.
New version of pallet which requires currency reservation & has slashing is introduced.
Tested using `try-runtime`.
**Check list**
=> Collator selection migration

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
Added support for `AccountKey20` to XCM precompile's `reserve_withdraw`.
**Check list**
=> XCM reserve-withdraw for 20bit address

.github/workflows/release.yml, .github/workflows/rpcTest.yml
Made rpc test step as a part of release. 
**Check list**
=> RPC tests as a  part of release

bin/collator/src/command.rs
Abolish default parachain id.
In case both `--parachain-id` flag and `paraId` in ChainSpec is missing, the node process will fail with an error.
By doing so, all networks can avoid being launched with unexpected configuration.
**Check list**
=> Abolish default parachain id

.github/workflows/rpcTest.yml, rpc-tests/config.js
Add parachain id flag to collator in polkadot launch
**Check list**
=> Added parachain id in rpc test

bin/collator/res/rocstar.json, bin/collator/res/rocstar.raw.json, bin/collator/res/shiden.json, bin/collator/res/shiden.raw.json, bin/collator/res/tokyo.json, bin/collator/res/tokyo.raw.json
Updated test network bootnodes & added 1 shiden bootnode.
- Tokyo Relay
- Rocstar
- Shiden
=> Boot node updates

Cargo.lock, runtime/local/Cargo.toml, runtime/local/src/lib.rs, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs
Enabled dApps Staking chain-extension on local & Shibuya
Close [PR #658](https://github.com/AstarNetwork/Astar/pull/658)
**Check list**
=> dApp-staking chain-extension to Local & Shibuya

rpc-tests/config.js, third-party/polkadot-launch/config.json
Fixes issue where RPC tests don't start because block production for parachain doesn't start.
=> RPC test config fix

bin/collator/res/astar.json, bin/collator/res/astar.raw.json, bin/collator/res/shibuya.json, bin/collator/res/shibuya.raw.json
=> added bootnodes

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
* removed `OnRuntimeUpgrade` hook from astar runtime for elasticity setting
* uplifted `astar-frame` repo to latest revision (dapps-staking bump & evm deps cleanup)
**Check list**
=> OnRuntimeUpgrade cleanup and astar-frame bump

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
=> Bump substrate version

bin/collator/res/astar.json, bin/collator/res/astar.raw.json, bin/collator/res/shibuya.json, bin/collator/res/shibuya.raw.json, bin/collator/res/shiden.json, bin/collator/res/shiden.raw.json
Change 5 bootnodes configuration to websocket to enable light client support
**Check list**
=> add websocket bootnodes

runtime/shiden/MANIFESTO.md
Adds the Shiden DAO manifesto to the Shiden runtime folder. This does not contain any runtime changes, only docs.
**Check list**
=> add Shiden DAO manifesto

rpc-tests/package.json, rpc-tests/tests/compile.js, rpc-tests/tests/contract.js, rpc-tests/tests/contracts/hello.sol, rpc-tests/tests/deploy.js, rpc-tests/tests/test-rpc.js, rpc-tests/yarn.lock
=> Added EVM tests

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/local/src/chain_extensions.rs, runtime/local/src/lib.rs, runtime/shibuya/Cargo.toml, runtime/shibuya/src/chain_extensions.rs, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
This is https://github.com/AstarNetwork/astar-frame/pull/109 PR companion that integrates new approach for CE integration.
**Check list**
=> Refactored chain extensions integration

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
Introduces partial fee burning on Astar, make it equivalent with Shiden.
Docs update: https://github.com/AstarNetwork/astar-docs/pull/112
**Check list**
=> Astar partial fee burning

Cargo.lock, bin/collator/Cargo.toml, bin/collator/src/local/chain_spec.rs, bin/collator/src/parachain/chain_spec/astar.rs, bin/collator/src/parachain/chain_spec/shibuya.rs, bin/collator/src/parachain/chain_spec/shiden.rs, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shiden/Cargo.toml
Explicitly specify number of decimals and symbol for test chains.
This will resolve the problematic (and irritating) incorrect number of decimals in polkadot-js.
**Check list**
=> Correct decimals and symbol for test chains

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/local/src/lib.rs, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml
Add proxy types in Shibuya.
Related to https://github.com/AstarNetwork/Astar/issues/760
**Check list**
=> add proxy types in shibuya

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml
Uplifts `pallet-xvm` to include latest fix for double EVM gas charging when called from another VM.
Affects `local-runtime` & `shibuya-runtime`.
**Check list**
=> XVM - fixed EVM double charging

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
Uplifts `pallet-custom-signatures` to include latest fix.
**Check list**
=> Custom sig uplift

bin/collator/res/rocstar.json, bin/collator/res/rocstar.raw.json
Updated rocstar bootnodes to avoid incorrect bootnode error
=> updated rocstar bootnodes

bin/collator/res/tokyo.json, bin/collator/res/tokyo.raw.json
=> added tokyo light client boot nodes

bin/collator/res/tokyo.json, bin/collator/res/tokyo.raw.json
=> fix tokyo bootnodes identity

Cargo.lock, bin/collator/Cargo.toml, bin/collator/res/shibuya.json, bin/collator/res/shibuya.raw.json, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shiden/Cargo.toml
This PR fix shibuya testnet block production.
**Check list**
=> Update shibuya chainspec, revert after bad upgrade

bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml
This PR reduces Astar Network block reward by 5% as agreed in https://forum.astar.network/t/halve-collator-rewards-on-astar-to-improve-decentralization/4117
**Note**
Before runtime upgrade reward distribution should be rebalanced.
**Check list**
=> Reduce Astar block reward

.github/README.md
Added README for benchmarking job
=> Readme benchmarks

Cargo.lock, bin/collator/Cargo.toml
=> Fix package versions

.github/workflows/release.yml
Fix Release build CI workflow, to use correct github action runner
=> Fix release build ci

bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
Enabled ProxyType Any for shiden
**Check list**
=> Enabled ProxyType Any for shiden

bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
=> Revert ProxyType Any for shiden

Cargo.lock, bin/collator/Cargo.toml, bin/collator/src/cli.rs, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shiden/Cargo.toml
Create flag for `enable-evm-rpc` parameter.
**Check list**
=> Fix enable-evm-rpc cli flag

.github/scripts/generate-release-body.ts, .github/workflows/release.yml
=> Fix release mac binary name

.github/workflows/release.yml, Cargo.lock, bin/collator/Cargo.toml, bin/xcm-tools/Cargo.toml, runtime/astar/Cargo.toml, runtime/astar/build.rs, runtime/astar/src/lib.rs, runtime/contracts-migration/Cargo.toml, runtime/local/Cargo.toml, runtime/local/build.rs, runtime/local/src/lib.rs, runtime/shibuya/Cargo.toml, runtime/shibuya/build.rs, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/build.rs, runtime/shiden/src/lib.rs, rust-toolchain.toml
Uplifts `Astar` repo from `polkadot-v0.9.36` to `polkadot-v0.9.37`.
**Check list**
=> polkadot-v0.9.37 uplift

bin/collator/res/astar.json, bin/collator/res/astar.raw.json
=> update boot node ID

.github/scripts/generate-release-body.ts
Updates prio list in the release template.
Adds explanation of what each release priority means.
=> Update release prios in template

Cargo.lock, Cargo.toml, README.md, bin/collator/Cargo.toml, bin/collator/build.rs, bin/collator/src/benchmarking.rs, bin/collator/src/command.rs, bin/xcm-tools/Cargo.toml, bin/xcm-tools/build.rs, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/local/src/lib.rs, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs, tests/xcm-simulator/Cargo.toml, tests/xcm-simulator/src/mocks/msg_queue.rs, tests/xcm-simulator/src/mocks/parachain.rs, tests/xcm-simulator/src/tests.rs
Utilize workspace inheritance for `Astar` repo.
No version bumps are on purpose.
=> Workspace inheritance

bin/collator/src/command.rs
This PR contains quick fix for clippy checks.
**Check list**
=> Quick fix for clippy checks

Cargo.lock, Cargo.toml, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/local/src/chain_extensions.rs, runtime/local/src/lib.rs, runtime/shibuya/Cargo.toml, runtime/shibuya/src/chain_extensions.rs, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml
Astar-frame pallet assets on Local + Shibuya
**Check list**
=> Astar-frame pallet assets Chain extension on Local + Shibuya

Cargo.lock
This PR introduce frontier bug fix patch, runtime specs should be updated.
**Check list**
=> Frontier from/to address fix for eth_call RPC

bin/collator/res/astar.json, bin/collator/res/astar.raw.json, bin/collator/res/shibuya.json, bin/collator/res/shibuya.raw.json, bin/collator/res/shiden.json, bin/collator/res/shiden.raw.json
New WSS URLs for bootnodes have been updated on chainspecs.
**Check list**
=> Update WSS bootnodes URL

rpc-tests/rpc-tests.toml, rpc-tests/tests/0001-register-xcasset.js, rpc-tests/tests/0001-transfer-reserve-asset-to-sibling.js
=> fixes registration and transfer for xcm v3

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml
This PR adds new proxy types on Shibuya. Previous Iteration: https://github.com/AstarNetwork/Astar/pull/778
Related https://github.com/AstarNetwork/Astar/issues/760
**Check list**
**Balances**
All Runtime calls from Pallet Balances allowed for proxy account
**Assets**
All Runtime calls from Pallet Assets allowed for proxy account
=> feat: update proxy types for shibuya and update specs

.github/workflows/enforce-labels.yml, README.md
This PR adds workflow which makes it mandatory to add a label on all PRs.
client, runtime, ci, tests, other
=> feat: enforce pr labels

.github/workflows/release.yml
Github Action: https://github.com/AstarNetwork/Astar/actions/runs/4916243149
Release Draft: https://github.com/AstarNetwork/Astar/releases/tag/untagged-aa0531c973965fa06fde
**Check list**
=> Ci tracing artifacts (Merge to feat/ci-tracing-artifacts)

Cargo.lock, runtime/astar/src/lib.rs, runtime/local/src/lib.rs, runtime/shibuya/src/lib.rs, runtime/shiden/src/lib.rs
Bump to latest `pallet-evm` version so we can include `WeightInfo`.
No semver of spec_version bump on purpose (already handled by other PRs).
=> EVM withdraw WeightInfo

runtime/shiden/src/lib.rs
Bump `Shiden` spec version.
**Check list**
=> Bump shiden spec version

.github/workflows/static-analysis.yml
=> adding runner disk cleanup to workflow

.github/workflows/base_checks.yaml, .github/workflows/benchmark.yml, .github/workflows/release.yml, .github/workflows/runtime-upgrade-test.yaml, .github/workflows/tests.yaml
=> Removes Android libs in runner machine to save some disk space

bin/collator/res/astar.json, bin/collator/res/astar.raw.json, bin/collator/res/shiden.json, bin/collator/res/shiden.raw.json
Switch Astar and Shiden bootnodes
**Check list**
=> Update Astar and Shiden all bootnodes

.github/workflows/coverage.yaml
=> coverage workflow - Free disk space

runtime/shibuya/src/lib.rs
Bump Shibuya Spec version
**Check list**
=> chore: bump shibuya spec

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
=> chore: release v5.18.0 prep

.github/workflows/base_checks.yaml, .github/workflows/coverage.yaml, .github/workflows/static-analysis.yml, .github/workflows/tests.yaml
=> Added concurrency for cancel previous runs

bin/collator/src/parachain/chain_spec/astar.rs, bin/collator/src/parachain/chain_spec/shiden.rs, runtime/astar/src/precompiles.rs, runtime/shiden/src/precompiles.rs
Minor change to make local `Astar`-dev and `Shiden`-dev deployments more consistent with the production state.
=> Remove revert code for dispatch

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml
For new release.
**Check list**
=> Bump Shibuya semver and spec versoin.

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
All runtimes spec versions are bumped.
**Check list**
=> v5.22.0 release prep

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
v5.23.0 release to include #1075 quick fix.
**Check list**
=> Release v5.23.0 prep

.github/license-check/config.json, .github/workflows/coverage.yaml
=> License check fix

Cargo.lock, Cargo.toml
Update `frontier` dependencies to include fix for Shiden RPC issue with `get_block_by_number`.
=> Shiden ethereum get_block_by_number fix

README.md
Update README.md with a link to Astar Network Audit Reports repo
**Check list**
=> Update README.md with a link to Astar Network Audit Reports repo

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
v0.27.0
**Astar**
- Added hybrid inflation model to Astar [#1103](https://github.com/AstarNetwork/Astar/pull/1103)
**Shibuya**
- Feat/au precompile [#1080](https://github.com/AstarNetwork/Astar/pull/1080)
=> v5.27.0 prep

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
Release prep for `v5.28.0` release.
* bumped spec_versions (precompile update) & crate semvers
* removed executed Astar `OnRuntimeUpgrade` logic
=> v5.28.0 release prep

rpc-tests/README.md
README only change to clean up typos and grammar issues.
**Check list**
=> fix: typo fixes and grammar

pallets/inflation/src/mock.rs, pallets/inflation/src/tests.rs
Changed total issuance and init inflation config in the `pallet-inflation` mock to be more realistic.
=> Inflation UT fix

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
Preparation for `v5.30.0` release.
Includes various minor dApp staking v3 updates & some dApps staking v2 adjustments for delegated claim.
=> Release v5.30.0 prep

Cargo.lock, README.md, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
Preparation for `v5.32.0` release.
Also included the rustdoc link into README.
=> Prep for v5.32.0 release

Cargo.lock, bin/collator/Cargo.toml, bin/xcm-tools/Cargo.toml, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
Checklist #1190 
**Check list**
=> feat: release v5.33.0 prep

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
Release prep work for `v5.35.0`.
=> v5.35.0 release prep

bin/collator/src/command.rs
These method is not needed anymore. I guess we can remove it to make clippy happy
=> cleanup command after last merge 

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
=> v5.38.0 release prep

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
Preparation for `v5.39.0` release.
=> Prep for v5.39.0 release

.github/workflows/e2e-tests.yaml
Doesn't change anything. Just make the command more explicit
=> update gh-e2e-tests build cmd

tests/e2e/tests/runtime-upgrade.test.ts
Fix console typo and minor changes
=> fix console typo

bin/collator/src/parachain/service.rs
The only code change required was `collation_request_receiver: None,` -> `collation_request_receiver: Some(request_stream),` but I thought to create 2 functions, 1 aura only and 1 for shell
=> fix aura consensus fallback

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
Spec version & crate semver bump for `v5.42.0` release prep.
=> Release v5.42.0 prep

.github/workflows/release.yml
seems like backport polkadot-sdk-1.9 not working
=> disable metadata hash

Cargo.lock, bin/collator/Cargo.toml, bin/collator/src/parachain/service.rs, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shiden/Cargo.toml
5.42.1 patch which uses equivocation import queue to better deal with forks
=> Use equivocation import queue

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shiden/Cargo.toml
=> Prep 5.42.2 release

.github/workflows/release.yml, runtime/astar/src/lib.rs, runtime/shibuya/src/lib.rs, runtime/shiden/src/lib.rs
Update versions after patch release
=> update versions after patch release

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
Prepare patch v5.43.1 to deploy collators slash fix
=> prep v5.43.1

.github/workflows/release.yml
=> fix build (optimised) gha

.github/workflows/release.yml
Cleans up some storage for `macos` build job.
=> MacOs CI disk cleanup

bin/collator/src/command.rs
This PR updates the revert command when running as Parachain. This was not the case since previous code was expecting the grandpa set which doesn't exist when running as Parachain but works fine when running a local dev since we run the local dev as Solo chain with grandpa enabled
The change checks if chain_spec is dev,
- if dev, then use grandpa set revert
- if not, then simply revert the chain without grandpa set
**Check list**
=> Fix revert command when running as parachain

primitives/src/governance.rs, runtime/shibuya/src/lib.rs
Allow the community council to unregister a dApp from the dApp staking protocol.
=> Community council dApp unregister

Cargo.lock, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
Preparation for the runtime-1300 release.
=> runtime-1300 release prep

Cargo.lock, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
`runtime-1400` release prep actions.
=> runtime-1400 release prep

pallets/dapp-staking/src/lib.rs, pallets/dapp-staking/src/test/tests.rs
This PR fixes a storage discrepancy detected during _try-state_ [tests](https://github.com/AstarNetwork/Astar/actions/runs/14080685255/job/39432747085): 
```bash
ERROR: ❌ "DappStaking" try_state checks failed: Other("Mismatch between Ledger total staked amounts and CurrentEraInfo total.")
```
The issue was caused by a mismatch in the eras of the `unstake_amount_iter` when unstaking from an unregistered contract. The iterator used the original era from the stake operation instead of the expected current or next era. As a result, `era_info` failed to update the current and next era total stakes correctly. This was reproduced by the `unstake_from_unregistered_matching_next_era_total_stake` test. Now the correct eras and unstake amount are used.
Additionally, assert …
=> fix: next era stake update after unstake from unregistered contract

Cargo.lock, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
=> runtime-1401 release prep

.github/workflows/zepter.yml, Cargo.lock, bin/collator/Cargo.toml, bin/collator/src/command.rs, bin/collator/src/evm_tracing_types.rs, bin/collator/src/local/service.rs, bin/collator/src/parachain/service.rs, bin/collator/src/rpc.rs, bin/collator/src/rpc/tracing.rs
Added a SQL as option for frontier db. Now it's possible to chose between rocksDB and SQL
Docs will be added to _docs.astar.network_
It creates a `frontier.db3` file for the sqlite db. 
Tested locally running a Shibuya collator:
```bash
~/astar-data/chains/shibuya/frontier/db
> sqlite3 frontier.db3
SQLite version 3.43.2 2023-10-10 13:08:14
Enter ".help" for usage hints.
sqlite> SELECT block_number, hex(ethereum_block_hash) as eth_hash, hex(substrate_block_hash) as substrate_hash, is_canon FROM blocks ORDER BY block_number DESC LIMIT 10;
324530|6842D718629DF7BEE8EA2E8F492B1B23879D0ABDE8ABBEE3DA101A63A76E84C8|61A1104AE411591487F040DD42AB288F813815EA3712D27341DE1EE7A30CFD17|1
324529|D384D7338C76E27F10936EE7BD869964A841CBC53CF4D5A05484C9D131708E0C|AC38912B5C146FD44E0B3 …
```
=> Added SQL backend

pallets/dapp-staking/README.md
Update dApp staking README to disambiguate part about unregister.
=> dApp staking Readme update

.github/scripts/generate-release-body.ts
Add recommended sidecar version to the release template.
=> Update release template

Cargo.lock, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
=> runtime-1601 prep

.github/workflows/check-try-state.yml
Closes #1488 
This PR introduces a try-state check workflow scheduled to run daily to automate dAppStaking try-state checks and catch state inconsistencies early, ensuring ongoing staking logic correctness.
=> TryState checks workflow

.github/workflows/release-runtime.yml
Partially addresses: https://github.com/AstarNetwork/Astar/issues/1484
=> Minor release runtime optimization

.github/workflows/benchmark.yml
=> Omni-bencher installation fix

.github/workflows/benchmark.yml
=> Omni bencher fix try5

precompiles/xcm/src/tests.rs
Minor update to XCM precompile test.
Closes #1221
=> Update XCM test

.github/workflows/zepter.yml
Fix for failing zepter CI job.
=> Zepter fix

Cargo.lock, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
=> Runtime-1700 prep
