AstarNetwork/Astar

ci/script.sh, nix/default.nix, nix/nixpkgs.nix, nix/release.nix, nix/shell.nix
No
* Added build & development support for NixOS systems (https://nixos.org/).
* Nix (https://nixos.org/nix/) package manager integration scripts placed in `nix` directory.
Start development environment with nightly wasm enabled rust compiler:
```bash
~/Plasm $ nix-shell ./nix/shell.nix
```
=> Added Nix integration scripts

bin/node/cli/res/custom_types.json
Inconsistent with RUST code. In my opinion the customer type should be corrected in this json file.
https://github.com/staketechnologies/Plasm/blob/8d242ed06c02ee86ba94eb947783f7b40b4b023f/frame/plasm-staking/src/parameters.rs#L20
* * *
=> Inconsistent with RUST code

Cargo.lock, bin/node/cli/Cargo.toml, bin/node/primitives/Cargo.toml, bin/node/rpc/Cargo.toml, bin/node/runtime/Cargo.toml, bin/node/runtime/src/lib.rs, frame/dapps-staking/src/lib.rs, frame/dapps-staking/src/mock.rs, frame/plasm-rewards/src/inflation.rs, frame/plasm-rewards/src/lib.rs, frame/plasm-rewards/src/mock.rs, frame/plasm-rewards/src/traits.rs, frame/plasm-validator/src/compute_era.rs, frame/plasm-validator/src/lib.rs, frame/plasm-validator/src/mock.rs, frame/plasm-validator/src/tests.rs
#136 
Added a simple algorithm to reward the Validator.
Along with that, I have refactored the algorithm to make it easier to change it.
* * *
=> First validator rewards

bin/subkey/src/main.rs
From ethereum public key, view to Ethereum address and Plasma address.
Execute:
```
subkey inspect <public_key(hex)>
```
* * *
=> Add claim into subkey

third-party/docker/plasm_builder/Dockerfile
Please consider changing the source image as `parity/rust-builder` is going to be deprecated.
=> New CI image

bin/node/cli/src/chain_spec.rs
When I run development mode by `plasm-node --dev`, only 1000 Unit is issued to development accounts. However, initializing contract requires more than 1000 Unit, and this is very inconvenient for developers.
So, I've increased the initial balance for testnet genesis to 1 Giga Units.
* * *
=> increase initial balance for testnet

.github/workflows/crates.yml, .github/workflows/crates_frame.yml, .github/workflows/dockerpush.yml, .github/workflows/integration.yml, Cargo.lock, Cargo.toml, bin/node/cli/Cargo.toml, frame/custom-signatures/Cargo.toml, frame/custom-signatures/src/ethereum.rs, frame/custom-signatures/src/lib.rs, third-party/nix/release.nix, third-party/nix/shell.nix
Custom signatures pallet helps to send transaction signed by the user-defined method.
Module definition.
```rust
pub trait Trait: frame_system::Trait {
/// The overarching event type.
type Event: From<Event<Self>> + Into<<Self as frame_system::Trait>::Event>;
/// A signable call.
type Call: Parameter + UnfilteredDispatchable<Origin=Self::Origin> + GetDispatchInfo;
/// User defined signature type.
type Signature: Parameter + Verify<Signer = Self::Signer>;
/// User defined signer type.
type Signer: IdentifyAccount<AccountId = Self::AccountId>;
/// A configuration for base priority of unsigned transactions.
///
/// This is exposed so that it can be tuned for particular runtime, when
/// multiple pallets send unsigned transactions.
type UnsignedPriority: Get<TransactionPriority>;
}
```
For …
=> Added custom signatures pallet

.gitmodules, Cargo.lock, bin/node/cli/Cargo.toml, bin/node/cli/src/chain_spec.rs, bin/node/cli/src/service.rs, bin/node/primitives/Cargo.toml, bin/node/primitives/src/lib.rs, bin/node/rpc/Cargo.toml, bin/node/rpc/src/lib.rs, bin/node/runtime/Cargo.toml, bin/node/runtime/build.rs, bin/node/runtime/src/lib.rs
Latest frontier & evm port for Plasm Rococo parachain.
* Created `rococo-v1` branch in [frontier](https://github.com/plasmnetwork/frontier) fork.
* Enabled frontier RPC services on collator node.
* Added frontier runtime API into parachain runtime.
* Added EVM and Ethereum pallets.
* Updated to latest cumulus & polkadot & substrate.
* * *
=> Enable EVM on Rococo parachain

bin/node/cli/src/chain_spec.rs
dusty.raw.json is recreated from bootnode1 node for Dusty5
chain_spec.rs is using dusty.raw.json
=> add raw genesis from running node

Cargo.lock, frame/custom-signatures/Cargo.toml, frame/custom-signatures/src/ethereum.rs, frame/custom-signatures/src/lib.rs, frame/custom-signatures/src/tests.rs
Fix issues reported by pallet audit.
* * *
=> Fix pallet custom signatures issues

frame/dapps-staking/src/pallet/mod.rs, frame/dapps-staking/src/testing_utils.rs, frame/dapps-staking/src/tests.rs
Implement pre-approved list for dApps contract registration
=> registration with pre-approved list of contracts

frame/dapps-staking/src/lib.rs, frame/dapps-staking/src/pallet/mod.rs, frame/dapps-staking/src/testing_utils.rs, frame/dapps-staking/src/tests.rs
Adding new storage double map to use as counter for accrued rewards per (contract, staker)
Add reward counter per contract
=> added counter for individual rewards

frame/dapps-staking/src/lib.rs, frame/dapps-staking/src/mock.rs, frame/dapps-staking/src/pallet/mod.rs, frame/dapps-staking/src/testing_utils.rs, frame/dapps-staking/src/tests.rs, frame/dapps-staking/src/traits.rs, runtime/local/src/lib.rs, runtime/shibuya/src/lib.rs
@akru @Dinonard
please take a look at this commit.
The implementation of trait `IsContract` is placed in runtime in order to reach EVM module.
But now the visibility of fn `is_contract` in pallet-dapps-staking is moved as well and compiler complains with:
`
no variant or associated item namedis_contractfound for enumtraits::SmartContractin the current scope
`
please advice what would be the best approach to solve this
=> SmartContract as trait

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
> Increase max number of stakers per contract in Shiden to 1024
**Check list**
**Changes**
- Max number of stakers per contract in Shiden
=> Shiden dapps staking - increase max stakers 512 -> 1024

runtime/shibuya/src/lib.rs, runtime/shiden/src/lib.rs
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**
=> Burn 20% of fees in shibuya (same as shiden)

.github/workflows/integration.yml
> Reduced retention for benchmarking binary
Reduced to 1 day. No need for it to take unnecessary space for more days.
This job is useful if you want to outsource binary building to the CI instead
of building it on your own machine.
**Check list**
=> Short retention for benchmarking binary.

Cargo.lock, bin/collator/Cargo.toml, bin/collator/src/parachain/chain_spec/astar.rs, bin/collator/src/parachain/chain_spec/shibuya.rs, bin/collator/src/parachain/chain_spec/shiden.rs, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shiden/Cargo.toml, third-party/polkadot-launch/config.json
Changed dev chains to be of `Development` type.
This allows all accounts to be accessible directly via Polkadot.js
app.
This is required to work with polkadot-launch tool.
Additionally, following changes were needed to make it work:
- in polkadot-launch
- modify `spawn.ts` file, function `startCollator` to exclude argument `--collator`
- when using template Astar/third-party/polkadot-launch/config.json
- set chain to `shibuya-dev` if testing shibuya
- set id to `2007` since that is the default parachain Id used by our binary (it's actually shiden id)
- remove `--force-authoring` as argument because polkadot-launch will add it without prior check 
**Check list**
=> Dev type chains

frame/dapps-staking/src/migrations.rs, frame/dapps-staking/src/pallet/mod.rs, runtime/shibuya/src/lib.rs, runtime/shiden/src/lib.rs
The purpose of this commit is to introduce a way for upgrading Shibuya.
Due to having huge amount of key-value pairs that require storage migration,
it's not possible to do it all in a single block. Therefore a concept of stateful runtime upgrade is introduced.
Basic idea is the following:
1. Do runtime_upgrade. Disable dApps Staking pallet extrinsic calls.
2. Manually call `do_upgrade` extrinsic call which will migrate storage until it consumes **W** weight.
* each call that doesn't finish the migration will save the state where it left off
3. Repeat 2. until migration is finished.
4. Re-enable the pallet extrinsic calls.
Code is a bit dirty and some operations should be handled in substrate code.
Feel free to comment, criticize and suggest improvements!
Note …
=> Stateful runtime upgrade

bin/collator/res/shibuya.json, bin/collator/res/shibuya.raw.json, bin/collator/res/shiden.json, bin/collator/res/shiden.raw.json
Update bootnode 1 IP and Key (same server)
Migrate bootnode 2 to EU
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**
=> Update migration of Shiden and Shibuya bootnodes

Cargo.lock, README.md, bin/collator/Cargo.toml, bin/collator/src/cli.rs, bin/collator/src/command.rs, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shiden/Cargo.toml
Use `RunCmd` struct from cumulus CLI instead of legacy substrate.
This makes us more consistent with other chains and allows us to use tools like `polkadot-launch`
without the need to modify them prior to usage.
**TODO**
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**
=> Cumulus RunCmd usage

.github/workflows/integration.yml
Nix build has been failing for quite some time due to timeout.
Since we don't store or use the built binary, `build` is swapped with `check`.
**Check list**
**Adds**
**Fixes**
**Changes**
**To-dos**
=> Swap nix build with check

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
This includes the Shiden runtime upgrade logic required for the fixed-era-length upgrade.
**Check list**
**Fixes**
addresses fixed-era-length issue on Shiden (astar-frame/fixed-era-length)
=> Shiden: dApps Staking 3.1.0 - fixed era lengths #552

Cargo.lock, bin/collator/Cargo.toml, bin/collator/src/parachain/chain_spec/shiden.rs, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
Adds `block-reward-v2` pallet to Shiden.
Reward distribution parameters are set to mimic legacy so when upgrade is executed,
no change will be visible in the reward distribution.
After we discuss possible parameters with community, we can change reward distribution config
via extrinsic call.
**Check list**
=> Shiden upgrade - block reward v2

Cargo.lock, bin/collator/Cargo.toml
Switches the global allocator from the system allocator to jemalloc, which is what Polkadot's using. This should both lower the CPU usage and the memory usage of the nodes.
**Check list**
=> Use `jemalloc` as the global allocator

.github/workflows/integration.yml
Fix for `astar-collator` binary not being executable after being downloaded in docker CI step.
=> Fix for astar-collator not being executable

.github/workflows/release.yml, Cargo.lock, bin/collator/Cargo.toml, bin/collator/src/cli.rs, bin/collator/src/command.rs, bin/collator/src/local/chain_spec.rs, bin/collator/src/parachain/chain_spec/astar.rs, bin/collator/src/parachain/chain_spec/shibuya.rs, bin/collator/src/parachain/chain_spec/shiden.rs, bin/xcm-tools/Cargo.toml, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/local/src/lib.rs, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
Uplift to `polkadot-v0.9.26` from previously used version `polkadot-v0.9.24`.
* reuse export wasm & genesis state commands from cumulus
* set all missing genesis config params to default
* relay number strict increase checker for Shiden & Astar
* relay number no check for Shibuya (due to relay changes)
* make use of improved construct_runtime macro
* contracts pallet updates
**Check list**
=> Uplift to polkadot v0.9.26

rpc-tests/tests/test-rpc.js, rpc-tests/tests/util.js
RPC tests cannot be verified before parachain start producing blocks. It starts after relaychain has produced 10 blocks. This PR have added wait for test suite to start when parachain start producing blocks. Test suite starts after parachain has produced at least 2 blocks.
**Check list**
=> For rpc tests checking parachain is producing blocks before testing

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shiden/Cargo.toml
Removes OnRuntimeUpgrade logic used to migrate collator-selection pallet from Astar runtime.
**Check list**
=> Remove collator selection upgrade hook from Astar

Cargo.lock, Cargo.toml, bin/collator/Cargo.toml, bin/collator/src/local/chain_spec.rs, bin/collator/src/parachain/chain_spec/astar.rs, bin/collator/src/parachain/chain_spec/shibuya.rs, bin/collator/src/parachain/chain_spec/shiden.rs, bin/collator/src/parachain/service.rs, bin/collator/src/rpc.rs, bin/xcm-tools/Cargo.toml, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/local/src/lib.rs, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs, rust-toolchain.toml
Uplifts `Astar` repo to use `polkadot-v0.9.28`.
**NOTE** - format check fails because if executed, it breaks the code in `local` runtime (will investigate)
**Check list**
=> Uplift to polkadot v0.9.28

bin/collator/src/command.rs
Default parachain id abolishment (raise error when parachain id not found in cli arg or chainspec) had a side effect on subcommands, since all subcommands load spec first and it cannot take `--parachain-id` cli arg. 
This PR recovers default parachain id functionality with a warning in case parachain id in cli arg mismatch one in the chainspec.
No semver updates since this PR is intended to be included in the next version release with other PR updates.
**Check list**
=> default parachain id

bin/collator/src/rpc.rs
Increases max allowed weight for non-transactional ETH calls 10 folds.
This can be useful for situations like with Graph where default settings don't work by default (e.g. 50_000_000 max gas).
Skipped updating semver since no changes were released yet.
Based on: https://github.com/paritytech/frontier/pull/799
=> 10 times max weight for non-tx eth calls

Cargo.lock, bin/collator/Cargo.toml, bin/collator/src/command.rs, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shiden/Cargo.toml
Fixed an issue where inappropriate runtime would be selected for a chain-spec in case its name doesn't start with `astar`, `shiden` or `shibuya`.
Also removed the default chain to be `shiden`. 
**Check list**
=> Node start selection change

Cargo.lock, runtime/astar/src/lib.rs, runtime/shibuya/src/lib.rs, runtime/shiden/src/lib.rs
Integrates `ManagerOrigin` for `XcAssetConfig` pallet.
This is useful because we can allow `SignedOrigin` to register cross-chain asset on Shibuya, resulting in EVM revert code being registered. Could also be used later on for Governance V2 if we want to have custom origin check for `XcAssetConfig` root-like access.
**TODO** - spec version and semver uplift will be done in https://github.com/AstarNetwork/Astar/pull/755
=> ManagerOrigin for xc-asset-config

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
Recent `frame-astar` contains XCM precompile for `assets_reserve_transfer`.
This PR bumps collator and runtime versions and spec versions and updates `xcm-primitives` dependency.
=> Bump versions for XCM `assets_reserve_transfer` precompile

Cargo.lock, bin/xcm-tools/Cargo.toml, bin/xcm-tools/src/cli.rs, bin/xcm-tools/src/command.rs
Extend `xcm-tools` with new command to calculate `Account32Hash`.
This is useful when processing `Transact` XCM instruction from non-sovereign-account origin.
=> Add account32hash to xcm-tools

bin/collator/res/shiden.json, bin/collator/res/shiden.raw.json
Migrate Shiden bootnode 2 server and switch it to WebSocket
**Check list**
=> migrate shiden bootnode2

Cargo.lock, bin/xcm-tools/Cargo.toml, bin/xcm-tools/src/cli.rs, bin/xcm-tools/src/command.rs
Adds support for `relay-chain-account` command for `xcm-tools`.
Useful when we need to generate relay chain's sovereign account.
=> Relay chain account command

bin/collator/res/astar.json, bin/collator/res/astar.raw.json, bin/collator/res/shibuya.json, bin/collator/res/shibuya.raw.json, bin/collator/res/shiden.json, bin/collator/res/shiden.raw.json
Adding bootnodes behing Secure Web Socket to allow smoldot sync.
2 bootnodes per network: Astar, Shiden and Shibuya
**Check list**
=> add wss bootnodes

Cargo.lock, bin/collator/Cargo.toml, bin/collator/src/parachain/chain_spec/astar.rs, bin/collator/src/parachain/chain_spec/shibuya.rs, bin/collator/src/parachain/chain_spec/shiden.rs, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shiden/Cargo.toml
Reduce number of `desired_candidates` in testnet genesis file.
Since max allowed candidates was reduced in runtimes, creating a genesis will fail.
**Check list**
=> Fix for desired candidates in genesis

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
Bump versions and update `pallet-evm-precompile-xcm` dependency to pull in https://github.com/AstarNetwork/astar-frame/pull/108 to allow `reserve_transfer` of native currency.
**Check list**
=> Support for native currency in `reserve_transfer`

Cargo.lock, bin/xcm-tools/Cargo.toml, bin/xcm-tools/src/cli.rs, bin/xcm-tools/src/command.rs
Expanded `account32-hash` command in `xcm-tools` with parameter which specifies network Id.
=> NetworkId for account32-hash command

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/local/src/lib.rs, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
This PR aims to improve pallet benchmarking.
1. Make use of whitelist storage keys introduced by https://github.com/AstarNetwork/astar-frame/pull/112 on astar-frame side.
2. Use macros to avoid code duplication (`define_benchmarks!`, `list_benchmarks!`, `add_benchmarks!`). See https://github.com/paritytech/substrate/pull/10592
Follow ups
- Bench dapps staking pallet and update weights in astar-frame
- Use new astar-frame package in Astar repo
**Check list**
=> Bench whitelist storage keys

runtime/shibuya/src/lib.rs
Allows both `Root` and `SignedOrigin` to manipulate Xc-asset config values for Shibuya.
=> Root or Signed for Shibuya's XC-asset config

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
Uplifts `xcm-precompile` to use latest version where `remote_transact` can accept native currency as payment asset.
astar-docs PR: [here](https://github.com/AstarNetwork/astar-docs/pull/157)
**Check list**
=> Uplift XCM precompile

Cargo.lock, bin/collator/Cargo.toml, bin/collator/src/local/service.rs, bin/collator/src/parachain/service.rs, bin/xcm-tools/Cargo.toml, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/local/src/lib.rs, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs, rust-toolchain.toml
Uplifts `Astar` from `polkadot-v0.9.30` to `polkadot-v0.9.33`.
This contains lots of changes, and overview can be read here:
* [v0.9.31 & v0.9.32](https://forum.polkadot.network/t/polkadot-release-analysis/1026)
* [v0.9.33](https://forum.polkadot.network/t/polkadot-release-analysis-v0-9-33/1287)
**Notable PRs**
The following is a condensed list of most impactful PRs.
* https://github.com/paritytech/substrate/pull/12358
* https://github.com/paritytech/substrate/pull/12421
* https://github.com/paritytech/cumulus/pull/1585
* https://github.com/paritytech/substrate/pull/11649
* https://github.com/paritytech/cumulus/pull/1782
**Check list**
=> Feat/polkadot v0.9.33

Cargo.lock, Cargo.toml, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/contracts-migration/Cargo.toml, runtime/contracts-migration/src/lib.rs, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
`pallet-contracts` **v9** storage migration can blow up in PoV size and this happened with Shibuya.
This PR provides an approach to migrate the storage in multiple steps.
* I wanted to avoid forking the `pallet-contracts` and doing the modification directly in there
* Most of the types needed from `pallet-contracts` are only available to `pallet-contracts` crate so they had to be redefined here
**NOTE**
It seems that PoV size is overestimated in the code (double the size we got with Shibuya upgrade).
As long as it's not underestimated it should be fine.
```
INFO main try-runtime::cli: TryRuntime_on_runtime_upgrade executed without errors. Consumed weight = (79450000000 ps, 47731515 byte), total weight = (500000000000 ps, 5242880 byte) (15.89 %, 910.41 %).
``` …
=> Contracts migration logic

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/local/src/lib.rs, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs, runtime/shiden/src/xcm_config.rs
Introduces latest `pallet-dapps-staking` version which introduces a new extrinsic call: `burn_stale_reward`
In case contract gets unregistered, its rewards will remain claimable for a predetermined number of eras.
After that, the new call can be used to burn the rewards.
* `Shiden` retention period is **7 eras**
* `Astar` retention period is **u32::MAX**, essentially disabling the functionality
Also introducing to `Shiden` is 100% fee burning. 
**Check list**
=> Shiden - DS burn functionality & 100% fee burn

.github/workflows/base_checks.yaml, .github/workflows/release.yml, .github/workflows/static-analysis.yml
- Abolish arduino protoc installation action
- rename MacOS artifacts (x86_64 -> aarch64)
- Linux cross compile (x86_64, aarch64)
https://github.com/AstarNetwork/Astar/releases/tag/untagged-a8bf445abf0d53504608
=> improve ci

runtime/astar/src/lib.rs, runtime/shibuya/src/lib.rs, runtime/shiden/src/lib.rs
Modified `Shiden` burning so only fee is burned, not the tip.
Also fixed `Shibuya`'s and `Astar`'s double burn.
No updates to semver or spec version is intentional.
=> Shiden - burn only fee, not the tip

.github/license-check/config.json, .github/license-check/headers/HEADER-GNUv3, .github/workflows/static-analysis.yml
Added license CI check for all `.rs` files.
=> License check CI

Cargo.lock, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
Added collator selection pallet to benchmarks so that we can benchmark this pallet by using astar-collator bin.
Once this is merged, a followup to update its weight here comes https://github.com/AstarNetwork/astar-frame/pull/123
=> add collator selection pallet to benchmarks

Cargo.lock, bin/collator/Cargo.toml, bin/collator/src/cli.rs, bin/collator/src/command.rs, bin/collator/src/local/service.rs, bin/collator/src/parachain/service.rs, bin/collator/src/rpc.rs, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shiden/Cargo.toml, third-party/zombienet/multi_parachains.toml, third-party/zombienet/single_parachain.toml
This PR is **client only**. It disables Ethereum compatible RPC servers by default.
Changelog:
* EVM RPC disabled by default;
* Introduced `--enable-evm-rpc` CLI flag that enables EVM RPC server.
**Check list**
=> Optional evm rpc

.github/workflows/benchmark.yml, .github/workflows/release.yml
Use the same github actions runner labels for binary build and benchmarks.
=> use same runner for build and benchmarks

Cargo.lock, bin/collator/Cargo.toml, bin/collator/src/cli.rs, bin/collator/src/local/service.rs, bin/collator/src/parachain/service.rs, bin/collator/src/rpc.rs, bin/collator/src/rpc/tracing.rs, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/local/src/lib.rs, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
Added transaction pool RPC methods:
* `txpool_content`
* `txpool_inspect`
* `txpool_status`
RPC methods enabled if `--ethapi=txpool` flag added.
Related astar-frame PR: https://github.com/AstarNetwork/astar-frame/pull/128
**Check list**
=> Added txpool rpc support

third-party/zombienet/multi_parachains.toml, third-party/zombienet/single_parachain.toml
Latest `zombienet` release adds some `.toml` checks that fails if file starts with a comment.
=> Zombienet toml fix

.github/workflows/base_checks.yaml, .github/workflows/release.yml
Current CI does not check for outdated/uncommitted `Cargo.lock`.
By passing `--locked` we ensure that lock file should be up to date.
=> Add `--locked` to cargo invocations

Cargo.lock, Cargo.toml, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/local/src/lib.rs, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
This integrates latest `pallet-contracts` dependencies into `Shibuya` and `Shiden` runtimes.
The `pallet-contract` adaptation can be seen [here](https://github.com/AstarNetwork/substrate/tree/polkadot-v0.9.37/pallet-contracts-latest).
**Check list**
=> Latest pallet-contracts integration

third-party/nix/nixpkgs.nix, third-party/nix/release.nix
Bumping Rust channel in Nix env.
When using Nix to build runtime with command `nix-shell -I nixpkgs=channel:nixos-21.05 third-party/nix/shell.nix --run "cargo build --release"` was failing due to old rustc version (although it should pick the correct one from rust-toolchain file). Builds fine after bumping rust in nix env.
**Check list**
=> chore: bump nix rust to match `rust-toolchain.toml`

Cargo.lock, tests/xcm-simulator/src/mocks/parachain.rs
Removes double implementation of unit tuple of `XcAssetExchanged` trait.
=> Fix double impl for XcAssetConfig in XcmSim

Cargo.lock, bin/collator/Cargo.toml, bin/collator/src/cli.rs, bin/collator/src/command.rs, bin/collator/src/local/service.rs, bin/collator/src/parachain/service.rs, bin/collator/src/rpc.rs, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/local/src/lib.rs, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
This PR introduce EVM tracing as optional feature. Using runtime overriding it makes possible to enable tracing on runtimes that don't have tracing runtime API.
New rust features:
* `evm-tracing` on runtimes: enable tracing runtime API when build with specified feature - used for tracing runtimes
* `evm-tracing` on collator: enable tracing RPC and host functions required for tracing runtimes.
Usage:
* download `tracing` node and runtime
* use `--wasm-runtime-overrides` flag to substitute tracing runtime instead of production
* EVM tracing API available on node
**Check list**
=> Plugable EVM tracing 

.github/workflows/base_checks.yaml, .github/workflows/release.yml, .github/workflows/static-analysis.yml
Modify CI to check & test without `evm-tracing` features enabled.
Also expands standard PR check to also include `evm-tracing` check.
However, this might need to be changed if the check proves to be too lenghty.
=> Fix CI to test code with & without EVM tracing

.github/scripts/generate-release-body.ts, .github/workflows/release.yml
Recover ubuntu aarch64 binary build in Release CI
Test build: https://github.com/AstarNetwork/Astar/actions/runs/4497253895
**Check list**
=> recover ubuntu aarch build in release ci

Cargo.lock, bin/collator/Cargo.toml, bin/collator/src/cli.rs, bin/collator/src/command.rs, bin/collator/src/parachain/service.rs
=> Add `ProposerFactory` limits to the cli

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/local/src/lib.rs, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
Adds `pallet-contracts` to `Astar`.
Cleans some code from `Shiden` and `Shibuya` related to `pallet-contracts` (minor).
**Check list**
=> Pallet contracts on Astar

bin/collator/src/cli.rs, bin/collator/src/command.rs, bin/collator/src/evm_tracing_types.rs, bin/collator/src/lib.rs, bin/collator/src/local/service.rs, bin/collator/src/parachain/service.rs, bin/collator/src/rpc/tracing.rs
This PR refactors some of the logic related to `evm-tracing` added in #883  
**Changes**
1.  utilize #[clap(flatten)] to organize EVM tracing related arguments into a single struct `EthApiOptions`
2.  move all `evm-tracing` related type into a separate module `evm-tracing-types.rs`
3. introduce `AdditionalConfiguration` struct for passing on additional arguments to the start_xyz_node functions.
=> feat: evm-tracing refactor

Cargo.lock, runtime/astar/src/lib.rs, runtime/shibuya/src/lib.rs, runtime/shiden/src/lib.rs
Version bumps & deps update to prepare for `v5.4.0` release.
This is needed due to the unexpected previous minor release.
**Check list**
=> Preparation for v5.4.0 release

runtime/shibuya/src/lib.rs
Updates `spec_version` for Shibuya which should have been included in https://github.com/AstarNetwork/Astar/pull/921
=> fix: update spec_version

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
This PR adds new proxy types on Shiden. Previous Iteration: #778 
Related #760 
```
CancelProxy,
DappsStaking,
```
```
Any,
NonTransfer,
Balances,
IdentityJudgement,
```
=> feat: Additional Proxy Types on shiden

CONTRIBUTING.md, README.md
Information regarding pr labels should be in CONTRIBUTING.md instead of README.md as was added in #924
=> docs: move labels info to contributions.md

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/local/Cargo.toml, runtime/local/src/lib.rs, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
Added a new proxy type StakerRewardClaim.
Only allows claim_staker call (and pallet-utility calls) to be executed.
This is less permissive than existing DappsStaking proxy type and is more appropriate for remote reward claim.
related to #856 
**Check list**
=> feat: add StakerRewardClaim proxy

.github/scripts/generate-release-body.ts
fix `generate-release-body.ts` file to allow printing of `pr` information  according to label. 
Broke due to Octokit API update.
=> patch: fix octokit api

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/astar/src/xcm_config.rs, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs, runtime/shiden/src/xcm_config.rs
* Updates `Astar` `SafeCallFilter` type to allow one-level composite calls
* Updates `Shiden` with additional call types
* Both `Astar` and `Shiden` are aligned
`EVM` and `WASM` smart contracts not enabled yet.
**Check list**
=> XCM Transact safe call filter update

bin/collator/res/astar.json, bin/collator/res/astar.raw.json
=> chore: remove legacy terminated Astar's OnFinality bootnodes

Cargo.lock, bin/collator/Cargo.toml, pallets/dapps-staking/Cargo.toml, pallets/dapps-staking/src/benchmarking.rs, pallets/dapps-staking/src/lib.rs, pallets/dapps-staking/src/tests.rs, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs, tests/xcm-simulator/src/tests/general.rs
Changes default reward destination from `StakeBalance` to `FreeBalance` for dApp staking.
Applies to all runtimes.
**Check list**
=> FreeBalance as default dapp-staking reward destination

.github/workflows/release.yml, README.md, rpc-tests/README.md, rpc-tests/rpc-tests.toml, rpc-tests/tests/0002-deploy-an-evm-contract.js, rpc-tests/tests/0002-get-evm-contract-data.js, rpc-tests/tests/0002-set-evm-contract-data.js
Fix incorrect param usage in RPC tests, and bump up zombienet version.
=> Fix rpc tests issues

rpc-tests/rpc-tests.toml
Latest version of **zombienet** takes WS port value to use for `--rpc-port` argument.
Although confusing, it is by design.
=> Fix for rpc port

.github/workflows/release.yml
Include runtime version in EVM tracing blobs
**Check list**
=> Add version to tracing runtimes

Cargo.lock, runtime/astar/Cargo.toml, runtime/astar/src/precompiles.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/precompiles.rs
This PR add batch-precompile to shiden and astar
**Check list**
=> add batch-precompile to shiden and astar

.github/workflows/stale.yml
Exempts project items from stale check to avoid them being deleted if not worked on for more than a month.
=> Exempt project items from stale check

runtime/astar/src/xcm_config.rs, runtime/shibuya/src/xcm_config.rs, runtime/shiden/src/xcm_config.rs
Removes unused XCM code to avoid confusion 🙂
=> Remove unused XCM consts

runtime/astar/src/xcm_config.rs, runtime/shibuya/src/xcm_config.rs, runtime/shiden/src/xcm_config.rs
Reduce default PoV size for XCM instructions.
This will soon be updated again with benchmarked values.
=> Reduce default PoV size for XCM instructions

pallets/unified-accounts/src/lib.rs, pallets/unified-accounts/src/tests.rs, runtime/shibuya/src/lib.rs
Fix the typo in mapping storage names.
Since it's already deployed in Shibuya testnet, we have two options.
1. Add migrations for this
2. Clear the pallet storage using sudo call, since it's only being used internally and total mappings are around 10
EDIT: using `OnRuntimeUpgrade` hook to clear the storage in Shibuya for corrupted mappings after the renaming.
**Check list**
=> fix: storage item typo in unified accounts

pallets/dapp-staking-v3/src/lib.rs, pallets/dapp-staking-v3/src/test/mock.rs, pallets/dapp-staking-v3/src/test/testing_utils.rs, pallets/dapp-staking-v3/src/test/tests.rs, pallets/dapp-staking-v3/src/test/tests_types.rs, pallets/dapp-staking-v3/src/types.rs
This is the **3rd part** of the `dApp staking v3` implementation.
* `stake` - covers staking locked funds on smart contracts
* `unstake` - covers unstaking staked funds from smart contracts
* `on_initialize` - covers `era` and `period` transitions (in the future might be replaced by `Scheduler`)
Given the functionality's complexity, the approach is taken to abstract as much of the _lower_ level
functionality into `structs` and `enums`.
* removed no longer used `LockedChunk` since we decided to only reward stakers, not lockers
* `ProtocolState` (holds general info about dApp staking) received various member functions/methods
* `AccountLedger` expanded with support for staking & unstaking
* `StakeAmount` enum is intended to encapsulate stake amount - will be more …
=> dApp staking v3 - part 3

Cargo.lock, chain-extensions/xvm/Cargo.toml, chain-extensions/xvm/src/lib.rs, runtime/local/src/chain_extensions.rs, runtime/local/src/lib.rs, runtime/shibuya/src/chain_extensions.rs, runtime/shibuya/src/lib.rs, tests/integration/src/setup.rs, tests/integration/src/xvm.rs
A quick fix for [the first part](https://github.com/AstarNetwork/Astar/issues/1033#issue-1914817309) of #1033. A default EVM address mapping would be added for the Wasm contract if:
- It's a payable call.
- There is no mapping yet.
**Check list**
=> XVM: default account mapping for Wasm contracts

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
`v5.21.0` includes XCM v2 precompile and fee alignment, which is the same with `v5.20.0` but for Shiden and Astar.
**Check list**
~- [ ] Zombienet test~ will do after draft release.
=> Release v5.21.0 prep

chain-extensions/types/xvm/src/lib.rs, chain-extensions/xvm/src/lib.rs, primitives/src/xvm.rs
Closes #1070
I tried to add an integration test to cover the checks, but the out-of-gas check in `pallet-contracts` has a big margin. i.e. it requires the weight limit to be much higher than the actual used weight, or the `OutOfGas` error is returned. @PierreOssun might have some info on this?
In addition to the issue above, the charged weight at the beginning of the CE is updated to all the gas left, instead of the gas left with a `30KB` dummy value.
**Check list**
=> XVM CE: Sufficient charged gas check before XVM execution.

runtime/astar/src/lib.rs, runtime/shibuya/src/lib.rs, runtime/shiden/src/lib.rs
It is changing from `Xtokens` to `XTokens`, as other parachains commonly use the latter.
There are no storage items in `orml-xtokens`, so storage migration is not needed.
**Check list**
=> orml-xtokens pallet name typo fix

.github/ISSUE_TEMPLATE/release_checklist.md, .github/PULL_REQUEST_TEMPLATE.md
Add release checklist in issue templates
**Check list**
=> chore: add issue template for release checklist

pallets/unified-accounts/src/lib.rs, pallets/unified-accounts/src/mock.rs, pallets/unified-accounts/src/tests.rs
This PR adds an additional check to make sure user has enough funds while charging AU storage fee while claiming accounts, so that account is not reaped.
This is required before `Mutate::burn_from()` as it burn user holdings with `Expendable` flag thus discarding the requirement to `Preserve` account from being repead.
**Check list**
=> fix(AU): [AST-1] prevent account from being reaped while charging fee

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
bump version for v5.26.0
Adding:
- XCM native fee reduction [#1092](https://github.com/AstarNetwork/Astar/pull/1092)
- fix(AU): [AST-1] prevent account from being reaped while charging fee [#1094](https://github.com/AstarNetwork/Astar/pull/1094)
- Add Hybrid Inflation to Shiden [#1095](https://github.com/AstarNetwork/Astar/pull/1095)
=> v5.26.0 prep

pallets/dapp-staking-v3/src/lib.rs, pallets/dapp-staking-v3/src/test/testing_utils.rs, pallets/dapp-staking-v3/src/test/tests.rs
Fix for an issue where `update_ledger` function would incorrectly set the _freeze_ for active locked amount,
instead of total locked amount.
This essentially meant that the unlocking chunks were not considered _locked_ or _frozen_.
Updated test utils that check this (many tests started failing immediately after that, without the fix of course).
=> Fix for incorrect freeze amount

Cargo.lock, pallets/dapps-staking/Cargo.toml, pallets/dapps-staking/src/pallet/mod.rs, pallets/dapps-staking/src/tests.rs
Introduces delegated functions for claiming staker rewards & changing reward destination.
This functionality is intended to be used during the transition period from _dApps Staking v2_ over to _dApp Staking v3_.
* introduces a new pallet state - `DecomissionStarted`
* this is a `semi-maintenance` mode, where most of the calls are prohibited & no new era changes occur
* once decommission has started, it is still possible to claim rewards, and delegated claiming becomes enabled
* to account for a situation where claiming into `StakeBalance` would cause an error due to too many chunks, setting reward destination also becomes delegated
* eras no longer change during decommissioning process since we want to avoid new rewards becoming available, thus prolonging the entire cleanup process
* …
=> dApps Staking v2 - claimStakerFor

tests/integration/src/unified_accounts.rs, tests/integration/src/xvm.rs, tests/xcm-simulator/src/mocks/parachain.rs
=> tests: fix typos

pallets/dapp-staking-v3/src/lib.rs, pallets/dapp-staking-v3/src/test/tests.rs
Adds _legacy wrapper_ into `dApp staking v3` to support two `dApps staking v2` calls:
* `unbond_and_unstake`
* `withdraw_from_unregistered`
This will allow users of the legacy Astar Native Ledger app to withdraw their funds after the v3 launch.
From the Ledger app:
```C
#define PD_CALL_DAPPSSTAKING_UNBOND_AND_UNSTAKE_V2 4
typedef struct {
pd_SmartContract_t contract_id;
pd_Compactu128_t amount;
} pd_dappsstaking_unbond_and_unstake_V2_t;
#define PD_CALL_DAPPSSTAKING_WITHDRAW_UNBONDED_V2 5
typedef struct {
} pd_dappsstaking_withdraw_unbonded_V2_t;
```
=> dApp Staking v3 - Legacy Ledger Support

pallets/dapp-staking-v3/src/lib.rs, pallets/dapp-staking-v3/src/migrations.rs, pallets/dapp-staking-v3/src/test/testing_utils.rs, pallets/dapp-staking-v3/src/test/tests.rs, pallets/dapp-staking-v3/src/test/tests_types.rs, pallets/dapp-staking-v3/src/types.rs, runtime/shibuya/src/lib.rs
Replaces the _sorted vector_ for rewards, with a `BTreeMap`.
This allows for efficient removal of entries from the tree, once reward has been claimed.
Error `DAppRewardAlreadyClaimed` has been removed.
Once dApp reward has been claimed for an era, further claim calls will result in
`NoClaimableRewards` error.
Also includes a minor storage migration, only to be used on Shibuya.
Moved all migration logic under a new module, for better readability.
Benchmarks will be re-run at another time.
=> dApp Staking v3 - Rewards As Tree

Cargo.lock, pallets/dapp-staking-v3/rpc/runtime-api/Cargo.toml, pallets/dapp-staking-v3/rpc/runtime-api/src/lib.rs, pallets/dapp-staking-v3/src/benchmarking/mod.rs, pallets/dapp-staking-v3/src/lib.rs, pallets/dapp-staking-v3/src/test/tests.rs, runtime/local/src/lib.rs, runtime/shibuya/src/lib.rs
Extends the dApp staking runtime API with two additional calls:
- `periods_per_cycle()` - how many periods occur in a single inflation cycle
- `get_dapp_tier_assignment()` - returns dApps tier assignment based on the staked values at the called block
=> Expanded DappStakingApi

pallets/dapps-staking/src/pallet/mod.rs, pallets/dapps-staking/src/tests.rs
Adds `unbond_and_unstake` and `withdraw_unbonded` to calls supported in the decommissioning period.
This is needed for Ledger users who want to switch accounts since generic Ledger app won't be available
on the launch day.
=> dApp Staking v3 - Unbond During Decommission

pallets/dapp-staking-v3/src/test/testing_utils.rs, pallets/dapp-staking-v3/src/test/tests_types.rs, pallets/dapp-staking-v3/src/types.rs
Fixes an issue when loyalty status would persist even though staker fully unstaked during the `Voting` subperiod.
=> dApp Staking v3 - Incorrect Loyalty Status Fix

.github/workflows/coverage.yaml, pallets/astar-xcm-benchmarks/src/generic/benchmarking.rs, pallets/astar-xcm-benchmarks/src/mock.rs
- Fix a silly mistake in xcm benchmarks mock where fee currency was set worngly.
- Add `runtime-benchmarks` and `try-runtime` features in tarpaulin CI job
**Check list**
=> fix: `BuyExecution` xcm benchmark tests

pallets/inflation/src/lib.rs
* used `saturating_div` instead of pure division for integers
* add sanity check for inflation config (warning in case of _zero_)
=> Pallet inflation safety additions

pallets/dapp-staking-v3/src/benchmarking/mod.rs, pallets/dapp-staking-v3/src/benchmarking/utils.rs, pallets/dapp-staking-v3/src/test/tests.rs
Both a minor improvement & bug fix in claim staker rewards benchmark.
There were issues depending on whether the `Build&Earn` duration was longer or shorter than `EraRewardSpanLength`.
=> dApp staking v3 - claim staker benchmark fix

pallets/dapp-staking-v3/src/lib.rs, pallets/dapp-staking-v3/src/migrations.rs, pallets/dapp-staking-v3/src/test/testing_utils.rs, pallets/dapp-staking-v3/src/test/tests.rs, pallets/dapp-staking-v3/src/test/tests_types.rs, pallets/dapp-staking-v3/src/types.rs, pallets/inflation/src/lib.rs, runtime/shibuya/src/lib.rs
To provide more capacity for new dApps, when dApp is unregistered, it will be removed from `IntegratedDApps` storage.
The dApp Id will still remain occupied, but that can be resolved in [the future](https://github.com/AstarNetwork/Astar/issues/1152) when required.
- `NotOperatedDApp` error has been removed and completely replaced with `ContractNotFound` error
- `DAppInfo` struct has been changed, with field `state` being removed
- Removed executed migrations
=> Integrated dApps improvement

pallets/dapps-staking/src/pallet/mod.rs, pallets/dapps-staking/src/tests.rs
Allow delegated claim calls to be used outside of `Decommission` mode context.
This is because there are so many unclaimed rewards, delegated claiming will take days to finish.
And we don't want to stop dApp staking from generating rewards for a prolonged period of time.
=> Relaxed decommission mode

Cargo.lock, bin/collator/Cargo.toml, pallets/dapp-staking-migration/src/lib.rs, pallets/dapp-staking-migration/src/mock.rs, pallets/dapp-staking-migration/src/tests.rs, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shiden/Cargo.toml
Fix for migration logic to ensure unbonding chunks are released.
=> Fix migration logic

.github/scripts/generate-release-body.ts
Fix for an issue where generating release draft would fail since the requested repos no longer exists as dependencies.
=> Safe get compare links

.github/workflows/static-analysis.yml
Optimize `clippy` by skipping the WASM build.
Reduces execution time from ~10minutes to ~5minutes.
=> Skip WASM build for clippy

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
Prep work for `v5.36.0` release.
=> Prep for v5.36.0 release

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/astar/src/chain_extensions.rs, runtime/astar/src/lib.rs, runtime/astar/src/precompiles.rs, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs, runtime/shiden/src/precompiles.rs, tests/integration/src/lib.rs
- remove all previous migrations from only SHIDEN & SHIBUYA
- bump semver and spec version
Closes: #1225 (checklist)
=> feat: v5.37.0 release prep

bin/collator/src/command.rs
Use of state_version 1 is incorrect since chain was started with state_version 0.
Instead of generation genesis header manually we use substrate cmd
=> fix export genesis state

bin/collator/src/command.rs
This genesis state generated is incorrect. If we don't need it then better remove it
closes #1234
=> remove genesis state print

Cargo.lock, Cargo.toml, runtime/local/src/weights/pallet_balances.rs, runtime/shibuya/src/weights/pallet_balances.rs
Integrates `burn` extrinsic into all runtimes, using a custom fork of `pallet-balances` ([link](https://github.com/AstarNetwork/polkadot-sdk/tree/astar-release-polkadot-v1.3.0)).
=> burn extrinsic integration

bin/collator/src/local/service.rs, bin/collator/src/parachain/mod.rs, bin/collator/src/parachain/service.rs, bin/collator/src/parachain/shell_upgrade.rs, bin/collator/src/rpc.rs
Custom PendingCrateInherentDataProvider and AuraConsensusDataProvider implementation required by EVM RPC to support Shiden sync from genesis block when there was no AuraApi. The implementation returns error instead of panic
=> fix shiden genesis sync

.github/workflows/release.yml, .github/workflows/tests.yaml, Makefile, bin/collator/src/local/chain_spec.rs
Make `cargo-nextest` preferred option to run tests with fallback to `cargo test`.
`cargo-nextest` makes it easy to identify slow and leaky test and tests results are easy to read.
=> update tests to use cargo-nextest if present

.github/workflows/e2e-tests.yaml, .gitmodules
GH action will build Astar & Shiden runtimes and then runs e2e tests using newest runtime. This will give us insight if something changes. This doesn't affect anything on the project, just runs some tests. Although I may change this later when I have a better idea how to deal with snapshot changes.
=> gh action to run e2e tests

Cargo.lock, bin/collator/Cargo.toml, pallets/dapp-staking-v3/src/benchmarking/utils.rs, pallets/dapp-staking-v3/src/lib.rs, pallets/dapp-staking-v3/src/test/mock.rs, pallets/dapp-staking-v3/src/test/tests.rs, pallets/dapp-staking-v3/src/test/tests_types.rs, pallets/dapp-staking-v3/src/types.rs, precompiles/dapp-staking-v3/src/test/mock.rs, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/local/src/lib.rs, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs, tests/xcm-simulator/src/mocks/parachain.rs
Fixes an issue with threshold calculation in dApp staking.
The issue happens because the formula for tier threshold update did not account for threshold value saturation.
As `ASTR` price increased, so did the number of available slots, and as a result, thresholds saturated at the minimum possible value. Number of slots could keep increasing, while the thresholds remained the same.
But as ASTR price dropped, this brought a negative change in the number of slots. Since number of slots was way
larger than the base number of slots, this seemed as a larger change that it was supposed to be, in respect to the current threshold.
This fix changes the way threshold is calculated so that the `new_number_of_slots` is always compared to the `base_number_of_slots`. This way ensures thresholds are …
=> Base native currency price for dApp Staking

pallets/dapp-staking-v3/rpc/runtime-api/src/lib.rs, pallets/dapp-staking-v3/src/benchmarking/mod.rs, pallets/dapp-staking-v3/src/lib.rs, pallets/dapp-staking-v3/src/migration.rs, pallets/dapp-staking-v3/src/test/mock.rs, pallets/dapp-staking-v3/src/test/testing_utils.rs, pallets/dapp-staking-v3/src/test/tests.rs, pallets/dapp-staking-v3/src/test/tests_types.rs, pallets/dapp-staking-v3/src/types.rs, precompiles/dapp-staking-v3/src/test/mock.rs, primitives/src/dapp_staking.rs, runtime/astar/src/lib.rs, runtime/astar/src/weights/pallet_dapp_staking_v3.rs, runtime/local/src/lib.rs, runtime/shibuya/src/lib.rs, runtime/shibuya/src/weights/pallet_dapp_staking_v3.rs, runtime/shiden/src/lib.rs, runtime/shiden/src/weights/pallet_dapp_staking_v3.rs, tests/xcm-simulator/src/mocks/parachain.rs
In order to preserve `u8` for DAppTierRewards we can use each byte of u8 for `tier` and `rank`. This way there's no need for migration and it's backward compatible.
Since u8 has 2 bytes `0xff` `0b1111_1111` we can use the 1st byte for `tier` and 2nd byte for `rank`. Rank goes from `0..10` (higher is better). Meaning if you just enter a tier your rank is `0` and more staking will increase your ranking as you become close to next tier.
```rust
// RankedTier { tier: 1, rank: 10 } is represented as 0xa1
let tier: u8 = 0xa1 & 0x0f; // tier  1
let rank: u8 = 0xa1 >> 4;   // rank 10
```
Currently all values will be from `0..3` so `rank` will be zero. Rank will take place once we deploy it.
The simplest solution for reward distribution between ranks will be to define an additional reward per …
=> stakingv3: rank dapps in-between tiers

pallets/dapp-staking-v3/src/test/testing_utils.rs, pallets/dapp-staking-v3/src/test/tests.rs, pallets/dapp-staking-v3/src/test/tests_types.rs, pallets/dapp-staking-v3/src/types.rs
Fixes the issue where the `unstake` call wouldn't correctly update future era staked amount.
E.g. for a situation where we have:
* `staked: { era: 10, amount: 20 }, future_staked: { era: 11, amount: 21 }`
* staker calls `unstake(era: 10, amount: 5)`
* state is incorrectly updated to: `staked: {era: 10, amount: 15}, future_staked: {era: 11, amount: 21}`
* the future era amount isn't correctly reduced, resulting in `ContractStake` remaining too high for a contract
dApps might have ended up in higher tier than they were supposed to.
No actions will be taken around this - whatever dApps earned, it's theirs.
When `unstake` operation is performed on `SingularStakingInfo` struct, it will now correctly account for the scenario where potential future era amount also needs to be reduced.
=> Fix staked amount too high after unstake issue

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
Spec ver & crate semver bumps for `v5.41.0` release.
Also updated polkadot-sdk deps since the backport of metadata hash feature causes issues when trying to compile.
=> v5.41.0 release prep

pallets/dapp-staking-v3/src/lib.rs, pallets/dapp-staking-v3/src/test/testing_utils.rs, pallets/dapp-staking-v3/src/test/tests.rs
When `lock` is called, the `total_balance` needs to be compared against complete frozen balance in dApp staking.
RIght now, incorrect function was called which only returned amount which was actively locked (not undergoing the unlocking period).
=> Fix incorrect check for locked/frozen amount

pallets/dapp-staking-v3/src/lib.rs, pallets/dapp-staking-v3/src/test/tests.rs
Provide an approach to fix the account within an incosistent freeze state.
The approach is as simple as possible, reusing the `claim_unlocked` logic to clear unlocking chunks which are forcefully set to be immediately claimable.
=> Fix account call for freeze/lock inconsistency

bin/collator/res/shibuya.json, bin/collator/res/shibuya.raw.json
Wrong  node ID set on boot node shibuya 03. We need to revert the old node id setup.
**Check list**
=> revert node id

.devcontainer/devcontainer.json, .github/workflows/release.yml, scripts/sync-smoke.sh, third-party/zombienet/setup.sh, third-party/zombienet/smoke.sh, third-party/zombienet/smoke.toml, third-party/zombienet/smoke.zndsl
* Zombienet smoke test script/CI
* Add devcontainer config
* Rename chain sync CI
=> zombienet smoke test

.github/workflows/static-analysis.yml
Replace deprecated `actions-rs/clippy-check` with just pure `cargo clippy` to fix phantom job https://github.com/orgs/community/discussions/129952
=> CI: update clippy

runtime/shibuya/src/lib.rs
Added missing storage version settings for governance related pallets.
=> Add missing storage version setting for Shibuya governance

runtime/local/src/lib.rs, runtime/shibuya/src/lib.rs
Added missing tech committee permission for Shibuya & local.
Also allowed utility pallet to be used in collective proxy calls for easier lock/stake/unstake/unlock operations.
=> Missing governance permissions for Shibuya

runtime/local/src/lib.rs, runtime/shibuya/src/lib.rs
Adjusted `local` runtime params to make testing scenarios described in the docs easier.
Current timing was sometimes too fast, which made it difficult to detect certain changes.
Also added missing settings for `Shibuya` runtime in respect with setting oracle members.
Slightly modified timing params for democracy.
=> Minor governance param adjustment

.github/workflows/check-migrations.yml
Update check migration to use custom endpoint
=> update check-migration CI

vendor/rpc/debug/src/lib.rs, vendor/rpc/trace/src/lib.rs
Fix EVM tracing for older runtimes.
https://github.com/paritytech/polkadot-sdk/pull/1781 updated `initialize_block` to return `ExtrinsicInclusionMode` so for old runtimes we need to call older `initialize_block_before_version_5`
=> fix evm tracing for older runtimes

bin/collator/src/parachain/service.rs, bin/collator/src/parachain/shell_upgrade.rs
Remove BuildOnAccess as it's not need with this new implementation which is also preparation for async-backing
=> simplify shell to aura

Cargo.lock, Cargo.toml, bin/collator/Cargo.toml, bin/collator/src/cli.rs, bin/collator/src/command.rs, bin/collator/src/parachain/service.rs
Collator hardware benchmark to ensure relay-chain block import happens at expected time. Collator will print a warning if the minimum hardware requirement isn't meet.
=> Collator hardware benchmark

.github/workflows/release.yml
The issue with improperly propagated _features_ isn't present in `polkadot-v1.11.0` so we can re-enable the feature `on-chain-release-build`.
Tested locally by building only runtimes (previously it didn't work).
=> Re-enable on-chain-release-build flag

Cargo.lock, pallets/dapp-staking-v3/src/migration.rs, runtime/astar/src/lib.rs, runtime/shibuya/src/lib.rs, runtime/shiden/src/lib.rs
Adds `try-runtime` sanity checks to ensure new tier threshold amounts are within a given variation range as suggested in [this comment](https://github.com/AstarNetwork/Astar/pull/1306#discussion_r1705008594). The allowed percentage can be customized using the **ThresholdVariationPercentage** parameter.
Variations allowed by runtime:
- Astar - 10%
- Shiden - 10%
- Shibuya - 150%
The variation tolerated is significant on Shibuya given the static tier params percentages configured. However, I used the same calculation as Astar/Shiden: a percentage of the total Shibuya issuance when dApp Staking v3 was launched, so **147M** $SBY. Here are the expected amounts when testing with `try-runtime` in the `post_upgrade` hook:
```bash
[2024-08-07T12:21:26Z WARN …
```
=> chore: try-runtime variation check on new thresholds

Cargo.lock, bin/collator/Cargo.toml, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
Prepare new client & runtime release
=> prep v5.43.0

tests/e2e/package.json, tests/e2e/tests/runtime-upgrade.test.ts, tests/e2e/vitest.config.mts, tests/e2e/yarn.lock
Doing upgrade with migration may take more time to produce the block
=> increase timeout for upgrade test

Cargo.lock, Cargo.toml, runtime/astar/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shiden/Cargo.toml
=> remove unused deps

pallets/collator-selection/src/benchmarking.rs, pallets/collator-selection/src/lib.rs, pallets/collator-selection/src/tests.rs
Non candidates should be slash-able until lock period ends
Add call to update slash destination
=> fix non-candidate slashing

pallets/dapp-staking-v3/src/benchmarking/mod.rs, pallets/dapp-staking-v3/src/lib.rs, pallets/dapp-staking-v3/src/test/mock.rs, pallets/dapp-staking-v3/src/test/tests.rs, pallets/dapp-staking-v3/src/types.rs
This pull request enforces tests with `try-state` checks to ensure storage invariants are maintained.
Closes #1294 
Below are all the invariants checked, grouped by storage items.
1. [`PeriodInfo`] number in [`ActiveProtocolState`] must always be greater than the number of elements in [`PeriodEnd`].
2. Ensures the `era` number and `next_era_start` block number are valid.
1. [`NextDAppId`] must always be greater than or equal to the number of dapps in [`IntegratedDApps`].
2. [`NextDAppId`] must always be greater than or equal to the number of contracts in [`ContractStake`].
1. The number of entries in [`IntegratedDApps`] should not exceed the [`T::MaxNumberOfContracts`] constant.
1. The [`T::NumberOfTiers`] constant must always be equal to the number of …
=> dApp staking - `try-state` checks implemented

pallets/dapp-staking/src/test/tests_types.rs, pallets/dapp-staking/src/types.rs, precompiles/dapp-staking/src/lib.rs, precompiles/dapp-staking/src/test/mock.rs, precompiles/dapp-staking/src/test/tests_v2.rs, precompiles/dapp-staking/src/test/tests_v3.rs, tests/integration/src/dapp_staking.rs, tests/integration/src/governance.rs, tests/integration/src/setup.rs, tests/xcm-simulator/src/tests/general.rs
Chore task, remnant from the audit, to cleanup `pub` visibility.
=> dApp staking - crate visibility

primitives/src/governance.rs, runtime/shibuya/src/lib.rs
* reduce collective agreement requirement to _half_ from _two thirds_ to allow extending the council more easily
* modify duration of enactment/voting/launch periods & collective motion duration to make them easier to test (and detect unwanted activities)
=> Modify Shibuya governance params

pallets/collator-selection/src/mock.rs, pallets/dapp-staking/src/test/tests_types.rs, pallets/vesting-mbm/src/mock.rs, precompiles/dispatch-lockdrop/src/tests.rs, precompiles/sr25519/src/tests.rs, precompiles/substrate-ecdsa/src/tests.rs, precompiles/unified-accounts/src/tests.rs, precompiles/xcm/src/tests.rs, tests/xcm-simulator/src/mocks/msg_queue.rs
A small change set to fix the clippy lints.
There is one more warning
```
warning: lint `clippy::clone_double_ref` has been renamed to `suspicious_double_ref_op`
|
= help: use the new name `suspicious_double_ref_op`
= note: requested on the command line with `-A clippy::clone_double_ref`
= note: `#[warn(renamed_and_removed_lints)]` on by default
```
Mostly coming from upstream I think since I couldn't find it in our repo.
**Check list**
=> Fix clippy lints

.github/workflows/benchmark.yml, .github/workflows/coverage.yaml, .github/workflows/release-client.yml, .github/workflows/release-runtime.yml
Bump upload/download actions in Github CI.
Closes https://github.com/AstarNetwork/Astar/issues/1359
=> Bump CI upload/download actions (fix tarpaulin job)

Cargo.lock, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
Update shiden runtime parameters to support async backing and apply necessary upgrades
=> shiden: enable async backing

Cargo.lock, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
Prepare for the first runtime release.
Spec versions are bumped according to the new versioning schema.
Crates are bumped as well, but this might need to be revised later on since it might make things more confusing due to the overlap with the client version.
=> Runtime-1000 release prep

.github/scripts/generate-release-body.ts
Comparison link generation had an issue where a line without the commit hash would be matched, resulting in early return from the function (without the comparison link).
=> Fix comparison link generation

Cargo.lock, bin/collator/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/src/lib.rs
* release `v5.45.0` prep
* cleanup of Shibuya & Shiden executed migrations
=> v5.45.0 release prep

.github/workflows/check-migrations.yml, .github/workflows/e2e-tests.yaml, .github/workflows/runtime-upgrade-test.yaml, tests/e2e/package.json, tests/e2e/yarn.lock
=> update e2e-tests deps

Cargo.lock, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/local/Cargo.toml, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
Release prep for `runtime-1100` release.
=> runtime-1100 release prep

runtime/astar/src/genesis_config.rs, runtime/astar/src/lib.rs, runtime/local/src/genesis_config.rs, runtime/local/src/lib.rs, runtime/shibuya/src/genesis_config.rs, runtime/shibuya/src/lib.rs
* `Governance` proxy type
* minor refactoring of genesis config for init balances to simplify testing
=> Governance proxy

Cargo.lock, runtime/astar/Cargo.toml, runtime/astar/src/lib.rs, runtime/shibuya/Cargo.toml, runtime/shibuya/src/lib.rs, runtime/shiden/Cargo.toml, runtime/shiden/src/lib.rs
Preparation for the `runtime-1200` release.
=> runtime-1200 release prep

tests/integration/src/setup.rs
`WeightToFee` redundant mock was removed in https://github.com/AstarNetwork/Astar/pull/1388/commits/633982fada9f42a98e00500abc1c8600200f16c6.
This PR removes unused imports to fix warnings when performing integration tests.
=> fix: unused imports removed

runtime/astar/src/lib.rs, runtime/shibuya/src/lib.rs, runtime/shiden/src/lib.rs, tests/integration/src/setup.rs, tests/integration/src/xcm_api.rs
=> Fix for XCM payment api report

.github/workflows/coverage.yaml, rust-toolchain.toml, tarpaulin.toml
For test coverage
**Check list**
=> Bump tarpaulin version

chain-extensions/pallet-assets/src/mock.rs, pallets/astar-xcm-benchmarks/src/mock.rs, pallets/collator-selection/src/mock.rs, pallets/collective-proxy/src/mock.rs, pallets/dapp-staking/src/test/mock.rs, pallets/dynamic-evm-base-fee/src/mock.rs, pallets/ethereum-checked/src/mock.rs, pallets/inflation/src/mock.rs, pallets/price-aggregator/src/mock.rs, pallets/static-price-provider/src/mock.rs, pallets/unified-accounts/src/mock.rs, pallets/vesting-mbm/src/mock.rs, pallets/xc-asset-config/src/mock.rs, precompiles/assets-erc20/src/mock.rs, precompiles/dapp-staking/src/test/mock.rs, precompiles/dispatch-lockdrop/src/mock.rs, precompiles/sr25519/src/mock.rs, precompiles/substrate-ecdsa/src/mock.rs, precompiles/unified-accounts/src/mock.rs, precompiles/xcm/src/mock.rs, tests/xcm-simulator/src/mocks/parachain.rs, tests/xcm-simulator/src/mocks/relay_chain.rs
Resolves the issue https://github.com/AstarNetwork/Astar/issues/1350
The following implementations in mocks were wrapped with derive macro to use TestDefaultConfig:
- pallet_balances::Config
- pallet_migrations::Config
- frame_system::Config
- pallet_timestamp::Config
- pallet_assets::Config
- pallet_contracts::Config
**Check list**
=> Mocks updated to use TestDefaultConfig

pallets/dapp-staking/README.md, pallets/dapp-staking/src/benchmarking/mod.rs, pallets/dapp-staking/src/lib.rs, pallets/dapp-staking/src/migration.rs, pallets/dapp-staking/src/test/mock.rs, pallets/dapp-staking/src/test/testing_utils.rs, pallets/dapp-staking/src/test/tests.rs, pallets/dapp-staking/src/test/tests_types.rs, pallets/dapp-staking/src/types.rs, pallets/dapp-staking/src/weights.rs, pallets/inflation/src/lib.rs, precompiles/dapp-staking/DappsStakingV3.sol, precompiles/dapp-staking/src/lib.rs, precompiles/dapp-staking/src/test/mock.rs, precompiles/dapp-staking/src/test/tests_v3.rs, runtime/astar/src/lib.rs, runtime/astar/src/weights/pallet_dapp_staking.rs, runtime/local/src/lib.rs, runtime/shibuya/src/lib.rs, runtime/shibuya/src/weights/pallet_dapp_staking.rs, runtime/shiden/src/lib.rs, runtime/shiden/src/weights/pallet_dapp_staking.rs, tests/xcm-simulator/src/mocks/parachain.rs
Closes #1379 
This PR introduces enhancements to the bonus reward eligibility mechanism and implements robust handling for stake movement, particularly during the `build&earn` subperiod.
The approach aims to first adapt existing pallet to easily support `move` functionality.
Pallet has a lot of tests covering stake & unstake functioality, and in case `MAX_BONUS_MOVES = 1`, every legacy test **must** work same as before.
* logic from `stake`, `unstake` and `unstake_from_unregistered` is moved to separate functions, with minimal modifications
* it's important for `unstake` to return more comprehensive information of what was unstaked
* _types_ are modified to return necessary information for the higher level functionality
* test files are adapted to ensure that high …
=> feat(dAppStaking): Move actions for bonus rewards

pallets/dapp-staking/src/test/tests.rs, pallets/dapp-staking/src/test/tests_types.rs, pallets/dapp-staking/src/types.rs
Fixes an invariant for the `SingularStakingInfo` type where the `previous_staked` value was updated with future stakes.
**Check list**
=> fix: `previous_staked` remains unchanged for future era stake amounts

pallets/dapp-staking/src/benchmarking/utils.rs, pallets/dapp-staking/src/lib.rs, pallets/dapp-staking/src/migration.rs, pallets/dapp-staking/src/test/mock.rs, pallets/dapp-staking/src/test/tests.rs, pallets/dapp-staking/src/test/tests_types.rs, pallets/dapp-staking/src/types.rs, runtime/astar/src/genesis_config.rs, runtime/astar/src/lib.rs, runtime/local/src/genesis_config.rs, runtime/shibuya/src/genesis_config.rs, runtime/shibuya/src/lib.rs, runtime/shiden/src/genesis_config.rs, runtime/shiden/src/lib.rs
Closes #1458 
Maximum percentages are derived from an Astar token price of **$0.05** (base values from dAppStaking v3 launch).
The `maximum_possible_percentage` value is optional. If is not specified, the default value used is 100% which reflects the entire total supply.
**Check list**
=> feat: dAppStaking max tier thresholds

.github/workflows/release-client.yml
arm build is failing due to openssl cross compiling error, so disabling it temp to unblock the release
**Check list**
=> ci: remove aarch64 build for now

pallets/dapp-staking/src/lib.rs, pallets/dapp-staking/src/test/testing_utils.rs, pallets/dapp-staking/src/test/tests.rs, pallets/dapp-staking/src/test/tests_types.rs, pallets/dapp-staking/src/types.rs
This PR fixes a bug that caused discrepancies in the voting stake in `EraInfo`, particularly during unstake or move operations.
Previously, the `EraInfo::unstake_amount` method incorrectly aggregated the unstaked **voting** and **build_and_earn** stakes using the `total` method, and subtracted the combined amount starting with **build_and_earn**. While this logic was acceptable for the current era (due to delayed staking eligibility after a move), it was incorrect for the next era leading to an inflated voting stake.
- Replaced the total-based subtraction in `EraInfo::unstake_amount` with a new `subtract_stake` method that subtracts **voting** and **build_and_earn** balances independently.
- Applied the same fix to `ContractStake` to ensure consistency across …
=> Fix: Era Info voting stake discrepancy when performing unstake/move operations

primitives/src/lib.rs, runtime/astar/src/lib.rs, runtime/shibuya/src/lib.rs, runtime/shiden/src/lib.rs, tests/xcm-simulator/src/mocks/parachain.rs
Fix `GasLimitPovSizeRatio` for all of our runtimes.
Both Kusama & Polkadot have increased max PoV size from **5MiB** to **10MiB**.
This will increase effective gas price by 2x, instead of 4x how it happened after the async backing upgrade.
It's an increase, but it's the correct approach according to the formula.
In addition, using 'custom' MAX_POV_SIZE of 10 MiB to reflect what's actually used live on Polkadot & Kusama.
=> GasLimitPovSizeRatio fix

Cargo.lock, Cargo.toml
Bump `frontier` to latest deps.
Using `rev` to avoid bumping polkadot-sdk dependecies (lots of backports in the `stable2412` branch).
=> Frontier dep bump

runtime/shiden/src/lib.rs
I somehow missed to modify Shiden spec version prior to the 1601 release.
This PR fixes it.
=> Shiden spec version fix

primitives/src/governance.rs, runtime/astar/src/lib.rs
Allows tech committee or main council to enable/disable maintenance mode in dApp staking.
This can be used to allow for a quicker reaction in case of an emergency.
=> Allow tech comm & council to trigger maintenance

scripts/run_benchmarks.sh
Updates benchmark script by removing the optimization.
The reason is that PoV calculation doesn't work when JSON file is used as input.
=> Benchmark script update
